"use strict";
/*
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthenticationDecision = void 0;
class AuthenticationDecision {
    static getAttributeTypeMap() {
        return AuthenticationDecision.attributeTypeMap;
    }
}
exports.AuthenticationDecision = AuthenticationDecision;
AuthenticationDecision.discriminator = undefined;
AuthenticationDecision.attributeTypeMap = [
    {
        "name": "status",
        "baseName": "status",
        "type": "AuthenticationDecision.StatusEnum"
    }
];
(function (AuthenticationDecision) {
    let StatusEnum;
    (function (StatusEnum) {
        StatusEnum["Proceed"] = "proceed";
        StatusEnum["Refused"] = "refused";
    })(StatusEnum = AuthenticationDecision.StatusEnum || (AuthenticationDecision.StatusEnum = {}));
})(AuthenticationDecision = exports.AuthenticationDecision || (exports.AuthenticationDecision = {}));
//# sourceMappingURL=authenticationDecision.js.map