"use strict";
/*
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Purchase = void 0;
class Purchase {
    static getAttributeTypeMap() {
        return Purchase.attributeTypeMap;
    }
}
exports.Purchase = Purchase;
Purchase.discriminator = undefined;
Purchase.attributeTypeMap = [
    {
        "name": "date",
        "baseName": "date",
        "type": "Date"
    },
    {
        "name": "merchantName",
        "baseName": "merchantName",
        "type": "string"
    },
    {
        "name": "originalAmount",
        "baseName": "originalAmount",
        "type": "Amount"
    }
];
//# sourceMappingURL=purchase.js.map