"use strict";
/*
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RelayedAuthenticationResponse = void 0;
class RelayedAuthenticationResponse {
    static getAttributeTypeMap() {
        return RelayedAuthenticationResponse.attributeTypeMap;
    }
}
exports.RelayedAuthenticationResponse = RelayedAuthenticationResponse;
RelayedAuthenticationResponse.discriminator = undefined;
RelayedAuthenticationResponse.attributeTypeMap = [
    {
        "name": "authenticationDecision",
        "baseName": "authenticationDecision",
        "type": "AuthenticationDecision"
    }
];
//# sourceMappingURL=relayedAuthenticationResponse.js.map