"use strict";
/*
 * The version of the OpenAPI document: v68
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateSessionResponse = void 0;
class CreateSessionResponse {
    static getAttributeTypeMap() {
        return CreateSessionResponse.attributeTypeMap;
    }
}
exports.CreateSessionResponse = CreateSessionResponse;
CreateSessionResponse.discriminator = undefined;
CreateSessionResponse.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "installationId",
        "baseName": "installationId",
        "type": "string"
    },
    {
        "name": "merchantAccount",
        "baseName": "merchantAccount",
        "type": "string"
    },
    {
        "name": "sdkData",
        "baseName": "sdkData",
        "type": "string"
    },
    {
        "name": "store",
        "baseName": "store",
        "type": "string"
    }
];
//# sourceMappingURL=createSessionResponse.js.map