"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CardIdentification = void 0;
class CardIdentification {
    static getAttributeTypeMap() {
        return CardIdentification.attributeTypeMap;
    }
}
exports.CardIdentification = CardIdentification;
CardIdentification.discriminator = undefined;
CardIdentification.attributeTypeMap = [
    {
        "name": "expiryMonth",
        "baseName": "expiryMonth",
        "type": "string"
    },
    {
        "name": "expiryYear",
        "baseName": "expiryYear",
        "type": "string"
    },
    {
        "name": "issueNumber",
        "baseName": "issueNumber",
        "type": "string"
    },
    {
        "name": "number",
        "baseName": "number",
        "type": "string"
    },
    {
        "name": "startMonth",
        "baseName": "startMonth",
        "type": "string"
    },
    {
        "name": "startYear",
        "baseName": "startYear",
        "type": "string"
    },
    {
        "name": "storedPaymentMethodId",
        "baseName": "storedPaymentMethodId",
        "type": "string"
    }
];
//# sourceMappingURL=cardIdentification.js.map