"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Card = void 0;
class Card {
    static getAttributeTypeMap() {
        return Card.attributeTypeMap;
    }
}
exports.Card = Card;
Card.discriminator = undefined;
Card.attributeTypeMap = [
    {
        "name": "cardHolder",
        "baseName": "cardHolder",
        "type": "PartyIdentification"
    },
    {
        "name": "cardIdentification",
        "baseName": "cardIdentification",
        "type": "CardIdentification"
    }
];
//# sourceMappingURL=card.js.map