"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConfirmationTrackingData = void 0;
class ConfirmationTrackingData {
    static getAttributeTypeMap() {
        return ConfirmationTrackingData.attributeTypeMap;
    }
}
exports.ConfirmationTrackingData = ConfirmationTrackingData;
ConfirmationTrackingData.discriminator = undefined;
ConfirmationTrackingData.attributeTypeMap = [
    {
        "name": "status",
        "baseName": "status",
        "type": "ConfirmationTrackingData.StatusEnum"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "ConfirmationTrackingData.TypeEnum"
    }
];
(function (ConfirmationTrackingData) {
    let StatusEnum;
    (function (StatusEnum) {
        StatusEnum["Credited"] = "credited";
    })(StatusEnum = ConfirmationTrackingData.StatusEnum || (ConfirmationTrackingData.StatusEnum = {}));
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["Confirmation"] = "confirmation";
    })(TypeEnum = ConfirmationTrackingData.TypeEnum || (ConfirmationTrackingData.TypeEnum = {}));
})(ConfirmationTrackingData = exports.ConfirmationTrackingData || (exports.ConfirmationTrackingData = {}));
//# sourceMappingURL=confirmationTrackingData.js.map