"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EstimationTrackingData = void 0;
class EstimationTrackingData {
    static getAttributeTypeMap() {
        return EstimationTrackingData.attributeTypeMap;
    }
}
exports.EstimationTrackingData = EstimationTrackingData;
EstimationTrackingData.discriminator = undefined;
EstimationTrackingData.attributeTypeMap = [
    {
        "name": "estimatedArrivalTime",
        "baseName": "estimatedArrivalTime",
        "type": "Date"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "EstimationTrackingData.TypeEnum"
    }
];
(function (EstimationTrackingData) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["Estimation"] = "estimation";
    })(TypeEnum = EstimationTrackingData.TypeEnum || (EstimationTrackingData.TypeEnum = {}));
})(EstimationTrackingData = exports.EstimationTrackingData || (exports.EstimationTrackingData = {}));
//# sourceMappingURL=estimationTrackingData.js.map