"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExternalReason = void 0;
class ExternalReason {
    static getAttributeTypeMap() {
        return ExternalReason.attributeTypeMap;
    }
}
exports.ExternalReason = ExternalReason;
ExternalReason.discriminator = undefined;
ExternalReason.attributeTypeMap = [
    {
        "name": "code",
        "baseName": "code",
        "type": "string"
    },
    {
        "name": "description",
        "baseName": "description",
        "type": "string"
    },
    {
        "name": "namespace",
        "baseName": "namespace",
        "type": "string"
    }
];
//# sourceMappingURL=externalReason.js.map