"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Lodging = void 0;
class Lodging {
    static getAttributeTypeMap() {
        return Lodging.attributeTypeMap;
    }
}
exports.Lodging = Lodging;
Lodging.discriminator = undefined;
Lodging.attributeTypeMap = [
    {
        "name": "checkInDate",
        "baseName": "checkInDate",
        "type": "string"
    },
    {
        "name": "numberOfNights",
        "baseName": "numberOfNights",
        "type": "number"
    }
];
//# sourceMappingURL=lodging.js.map