"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferNotificationCounterParty = void 0;
class TransferNotificationCounterParty {
    static getAttributeTypeMap() {
        return TransferNotificationCounterParty.attributeTypeMap;
    }
}
exports.TransferNotificationCounterParty = TransferNotificationCounterParty;
TransferNotificationCounterParty.discriminator = undefined;
TransferNotificationCounterParty.attributeTypeMap = [
    {
        "name": "balanceAccountId",
        "baseName": "balanceAccountId",
        "type": "string"
    },
    {
        "name": "bankAccount",
        "baseName": "bankAccount",
        "type": "BankAccountV3 | null"
    },
    {
        "name": "card",
        "baseName": "card",
        "type": "Card | null"
    },
    {
        "name": "merchant",
        "baseName": "merchant",
        "type": "TransferNotificationMerchantData | null"
    },
    {
        "name": "transferInstrumentId",
        "baseName": "transferInstrumentId",
        "type": "string"
    }
];
//# sourceMappingURL=transferNotificationCounterParty.js.map