"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BusinessLineInfoUpdate = void 0;
class BusinessLineInfoUpdate {
    static getAttributeTypeMap() {
        return BusinessLineInfoUpdate.attributeTypeMap;
    }
}
exports.BusinessLineInfoUpdate = BusinessLineInfoUpdate;
BusinessLineInfoUpdate.discriminator = undefined;
BusinessLineInfoUpdate.attributeTypeMap = [
    {
        "name": "industryCode",
        "baseName": "industryCode",
        "type": "string"
    },
    {
        "name": "salesChannels",
        "baseName": "salesChannels",
        "type": "Array<string>"
    },
    {
        "name": "sourceOfFunds",
        "baseName": "sourceOfFunds",
        "type": "SourceOfFunds | null"
    },
    {
        "name": "webData",
        "baseName": "webData",
        "type": "Array<WebData>"
    },
    {
        "name": "webDataExemption",
        "baseName": "webDataExemption",
        "type": "WebDataExemption | null"
    }
];
//# sourceMappingURL=businessLineInfoUpdate.js.map