"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CalculatePciStatusResponse = void 0;
class CalculatePciStatusResponse {
    static getAttributeTypeMap() {
        return CalculatePciStatusResponse.attributeTypeMap;
    }
}
exports.CalculatePciStatusResponse = CalculatePciStatusResponse;
CalculatePciStatusResponse.discriminator = undefined;
CalculatePciStatusResponse.attributeTypeMap = [
    {
        "name": "signingRequired",
        "baseName": "signingRequired",
        "type": "boolean"
    }
];
//# sourceMappingURL=calculatePciStatusResponse.js.map