"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CheckTaxElectronicDeliveryConsentResponse = void 0;
class CheckTaxElectronicDeliveryConsentResponse {
    static getAttributeTypeMap() {
        return CheckTaxElectronicDeliveryConsentResponse.attributeTypeMap;
    }
}
exports.CheckTaxElectronicDeliveryConsentResponse = CheckTaxElectronicDeliveryConsentResponse;
CheckTaxElectronicDeliveryConsentResponse.discriminator = undefined;
CheckTaxElectronicDeliveryConsentResponse.attributeTypeMap = [
    {
        "name": "US1099k",
        "baseName": "US1099k",
        "type": "boolean"
    }
];
//# sourceMappingURL=checkTaxElectronicDeliveryConsentResponse.js.map