"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetAcceptedTermsOfServiceDocumentResponse = void 0;
class GetAcceptedTermsOfServiceDocumentResponse {
    static getAttributeTypeMap() {
        return GetAcceptedTermsOfServiceDocumentResponse.attributeTypeMap;
    }
}
exports.GetAcceptedTermsOfServiceDocumentResponse = GetAcceptedTermsOfServiceDocumentResponse;
GetAcceptedTermsOfServiceDocumentResponse.discriminator = undefined;
GetAcceptedTermsOfServiceDocumentResponse.attributeTypeMap = [
    {
        "name": "document",
        "baseName": "document",
        "type": "string"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "termsOfServiceAcceptanceReference",
        "baseName": "termsOfServiceAcceptanceReference",
        "type": "string"
    },
    {
        "name": "termsOfServiceDocumentFormat",
        "baseName": "termsOfServiceDocumentFormat",
        "type": "GetAcceptedTermsOfServiceDocumentResponse.TermsOfServiceDocumentFormatEnum"
    }
];
(function (GetAcceptedTermsOfServiceDocumentResponse) {
    let TermsOfServiceDocumentFormatEnum;
    (function (TermsOfServiceDocumentFormatEnum) {
        TermsOfServiceDocumentFormatEnum["Json"] = "JSON";
        TermsOfServiceDocumentFormatEnum["Pdf"] = "PDF";
        TermsOfServiceDocumentFormatEnum["Txt"] = "TXT";
    })(TermsOfServiceDocumentFormatEnum = GetAcceptedTermsOfServiceDocumentResponse.TermsOfServiceDocumentFormatEnum || (GetAcceptedTermsOfServiceDocumentResponse.TermsOfServiceDocumentFormatEnum = {}));
})(GetAcceptedTermsOfServiceDocumentResponse = exports.GetAcceptedTermsOfServiceDocumentResponse || (exports.GetAcceptedTermsOfServiceDocumentResponse = {}));
//# sourceMappingURL=getAcceptedTermsOfServiceDocumentResponse.js.map