"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SetTaxElectronicDeliveryConsentRequest = void 0;
class SetTaxElectronicDeliveryConsentRequest {
    static getAttributeTypeMap() {
        return SetTaxElectronicDeliveryConsentRequest.attributeTypeMap;
    }
}
exports.SetTaxElectronicDeliveryConsentRequest = SetTaxElectronicDeliveryConsentRequest;
SetTaxElectronicDeliveryConsentRequest.discriminator = undefined;
SetTaxElectronicDeliveryConsentRequest.attributeTypeMap = [
    {
        "name": "US1099k",
        "baseName": "US1099k",
        "type": "boolean"
    }
];
//# sourceMappingURL=setTaxElectronicDeliveryConsentRequest.js.map