"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CancelTransfersRequest = void 0;
class CancelTransfersRequest {
    static getAttributeTypeMap() {
        return CancelTransfersRequest.attributeTypeMap;
    }
}
exports.CancelTransfersRequest = CancelTransfersRequest;
CancelTransfersRequest.discriminator = undefined;
CancelTransfersRequest.attributeTypeMap = [
    {
        "name": "transferIds",
        "baseName": "transferIds",
        "type": "Array<string>"
    }
];
//# sourceMappingURL=cancelTransfersRequest.js.map