"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DirectDebitInformation = void 0;
class DirectDebitInformation {
    static getAttributeTypeMap() {
        return DirectDebitInformation.attributeTypeMap;
    }
}
exports.DirectDebitInformation = DirectDebitInformation;
DirectDebitInformation.discriminator = undefined;
DirectDebitInformation.attributeTypeMap = [
    {
        "name": "dateOfSignature",
        "baseName": "dateOfSignature",
        "type": "Date"
    },
    {
        "name": "dueDate",
        "baseName": "dueDate",
        "type": "Date"
    },
    {
        "name": "mandateId",
        "baseName": "mandateId",
        "type": "string"
    },
    {
        "name": "sequenceType",
        "baseName": "sequenceType",
        "type": "string"
    }
];
//# sourceMappingURL=directDebitInformation.js.map