"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FindTransfersResponse = void 0;
class FindTransfersResponse {
    static getAttributeTypeMap() {
        return FindTransfersResponse.attributeTypeMap;
    }
}
exports.FindTransfersResponse = FindTransfersResponse;
FindTransfersResponse.discriminator = undefined;
FindTransfersResponse.attributeTypeMap = [
    {
        "name": "_links",
        "baseName": "_links",
        "type": "Links | null"
    },
    {
        "name": "data",
        "baseName": "data",
        "type": "Array<TransferData>"
    }
];
//# sourceMappingURL=findTransfersResponse.js.map