"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IssuingTransactionData = void 0;
class IssuingTransactionData {
    static getAttributeTypeMap() {
        return IssuingTransactionData.attributeTypeMap;
    }
}
exports.IssuingTransactionData = IssuingTransactionData;
IssuingTransactionData.discriminator = undefined;
IssuingTransactionData.attributeTypeMap = [
    {
        "name": "captureCycleId",
        "baseName": "captureCycleId",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "IssuingTransactionData.TypeEnum"
    }
];
(function (IssuingTransactionData) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["IssuingTransactionData"] = "issuingTransactionData";
    })(TypeEnum = IssuingTransactionData.TypeEnum || (IssuingTransactionData.TypeEnum = {}));
})(IssuingTransactionData = exports.IssuingTransactionData || (exports.IssuingTransactionData = {}));
//# sourceMappingURL=issuingTransactionData.js.map