"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferView = void 0;
class TransferView {
    static getAttributeTypeMap() {
        return TransferView.attributeTypeMap;
    }
}
exports.TransferView = TransferView;
TransferView.discriminator = undefined;
TransferView.attributeTypeMap = [
    {
        "name": "categoryData",
        "baseName": "categoryData",
        "type": "BankCategoryData | InternalCategoryData | IssuedCard | PlatformPayment | null"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "reference",
        "baseName": "reference",
        "type": "string"
    }
];
//# sourceMappingURL=transferView.js.map