"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferServiceRestServiceError = void 0;
class TransferServiceRestServiceError {
    static getAttributeTypeMap() {
        return TransferServiceRestServiceError.attributeTypeMap;
    }
}
exports.TransferServiceRestServiceError = TransferServiceRestServiceError;
TransferServiceRestServiceError.discriminator = undefined;
TransferServiceRestServiceError.attributeTypeMap = [
    {
        "name": "detail",
        "baseName": "detail",
        "type": "string"
    },
    {
        "name": "errorCode",
        "baseName": "errorCode",
        "type": "string"
    },
    {
        "name": "instance",
        "baseName": "instance",
        "type": "string"
    },
    {
        "name": "invalidFields",
        "baseName": "invalidFields",
        "type": "Array<InvalidField>"
    },
    {
        "name": "requestId",
        "baseName": "requestId",
        "type": "string"
    },
    {
        "name": "response",
        "baseName": "response",
        "type": "object"
    },
    {
        "name": "routingDetails",
        "baseName": "routingDetails",
        "type": "Array<RoutingDetails>"
    },
    {
        "name": "status",
        "baseName": "status",
        "type": "number"
    },
    {
        "name": "title",
        "baseName": "title",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    }
];
//# sourceMappingURL=transferServiceRestServiceError.js.map