"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferNotificationMerchantData = void 0;
class TransferNotificationMerchantData {
    static getAttributeTypeMap() {
        return TransferNotificationMerchantData.attributeTypeMap;
    }
}
exports.TransferNotificationMerchantData = TransferNotificationMerchantData;
TransferNotificationMerchantData.discriminator = undefined;
TransferNotificationMerchantData.attributeTypeMap = [
    {
        "name": "acquirerId",
        "baseName": "acquirerId",
        "type": "string"
    },
    {
        "name": "city",
        "baseName": "city",
        "type": "string"
    },
    {
        "name": "country",
        "baseName": "country",
        "type": "string"
    },
    {
        "name": "mcc",
        "baseName": "mcc",
        "type": "string"
    },
    {
        "name": "merchantId",
        "baseName": "merchantId",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "postalCode",
        "baseName": "postalCode",
        "type": "string"
    }
];
//# sourceMappingURL=transferNotificationMerchantData.js.map