"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferReview = void 0;
class TransferReview {
    static getAttributeTypeMap() {
        return TransferReview.attributeTypeMap;
    }
}
exports.TransferReview = TransferReview;
TransferReview.discriminator = undefined;
TransferReview.attributeTypeMap = [
    {
        "name": "numberOfApprovalsRequired",
        "baseName": "numberOfApprovalsRequired",
        "type": "number"
    },
    {
        "name": "scaOnApproval",
        "baseName": "scaOnApproval",
        "type": "TransferReview.ScaOnApprovalEnum"
    }
];
(function (TransferReview) {
    let ScaOnApprovalEnum;
    (function (ScaOnApprovalEnum) {
        ScaOnApprovalEnum["Completed"] = "completed";
        ScaOnApprovalEnum["NotApplicable"] = "notApplicable";
        ScaOnApprovalEnum["Required"] = "required";
    })(ScaOnApprovalEnum = TransferReview.ScaOnApprovalEnum || (TransferReview.ScaOnApprovalEnum = {}));
})(TransferReview = exports.TransferReview || (exports.TransferReview = {}));
//# sourceMappingURL=transferReview.js.map