"use strict";
/*
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferRequestReview = void 0;
class TransferRequestReview {
    static getAttributeTypeMap() {
        return TransferRequestReview.attributeTypeMap;
    }
}
exports.TransferRequestReview = TransferRequestReview;
TransferRequestReview.discriminator = undefined;
TransferRequestReview.attributeTypeMap = [
    {
        "name": "numberOfApprovalsRequired",
        "baseName": "numberOfApprovalsRequired",
        "type": "number"
    },
    {
        "name": "scaOnApproval",
        "baseName": "scaOnApproval",
        "type": "boolean"
    }
];
//# sourceMappingURL=transferRequestReview.js.map