"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffirmDetails = void 0;
class AffirmDetails {
    static getAttributeTypeMap() {
        return AffirmDetails.attributeTypeMap;
    }
}
exports.AffirmDetails = AffirmDetails;
AffirmDetails.discriminator = undefined;
AffirmDetails.attributeTypeMap = [
    {
        "name": "checkoutAttemptId",
        "baseName": "checkoutAttemptId",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "AffirmDetails.TypeEnum"
    }
];
(function (AffirmDetails) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["Affirm"] = "affirm";
    })(TypeEnum = AffirmDetails.TypeEnum || (AffirmDetails.TypeEnum = {}));
})(AffirmDetails = exports.AffirmDetails || (exports.AffirmDetails = {}));
//# sourceMappingURL=affirmDetails.js.map