"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Agency = void 0;
class Agency {
    static getAttributeTypeMap() {
        return Agency.attributeTypeMap;
    }
}
exports.Agency = Agency;
Agency.discriminator = undefined;
Agency.attributeTypeMap = [
    {
        "name": "invoiceNumber",
        "baseName": "invoiceNumber",
        "type": "string"
    },
    {
        "name": "planName",
        "baseName": "planName",
        "type": "string"
    }
];
//# sourceMappingURL=agency.js.map