"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Airline = void 0;
class Airline {
    static getAttributeTypeMap() {
        return Airline.attributeTypeMap;
    }
}
exports.Airline = Airline;
Airline.discriminator = undefined;
Airline.attributeTypeMap = [
    {
        "name": "agency",
        "baseName": "agency",
        "type": "Agency | null"
    },
    {
        "name": "boardingFee",
        "baseName": "boardingFee",
        "type": "number"
    },
    {
        "name": "code",
        "baseName": "code",
        "type": "string"
    },
    {
        "name": "computerizedReservationSystem",
        "baseName": "computerizedReservationSystem",
        "type": "string"
    },
    {
        "name": "customerReferenceNumber",
        "baseName": "customerReferenceNumber",
        "type": "string"
    },
    {
        "name": "designatorCode",
        "baseName": "designatorCode",
        "type": "string"
    },
    {
        "name": "documentType",
        "baseName": "documentType",
        "type": "string"
    },
    {
        "name": "flightDate",
        "baseName": "flightDate",
        "type": "Date"
    },
    {
        "name": "legs",
        "baseName": "legs",
        "type": "Array<Leg>"
    },
    {
        "name": "passengerName",
        "baseName": "passengerName",
        "type": "string"
    },
    {
        "name": "passengers",
        "baseName": "passengers",
        "type": "Array<Passenger>"
    },
    {
        "name": "ticket",
        "baseName": "ticket",
        "type": "Ticket | null"
    },
    {
        "name": "travelAgency",
        "baseName": "travelAgency",
        "type": "TravelAgency | null"
    }
];
//# sourceMappingURL=airline.js.map