"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApplePayDonations = void 0;
class ApplePayDonations {
    static getAttributeTypeMap() {
        return ApplePayDonations.attributeTypeMap;
    }
}
exports.ApplePayDonations = ApplePayDonations;
ApplePayDonations.discriminator = undefined;
ApplePayDonations.attributeTypeMap = [
    {
        "name": "applePayToken",
        "baseName": "applePayToken",
        "type": "string"
    },
    {
        "name": "checkoutAttemptId",
        "baseName": "checkoutAttemptId",
        "type": "string"
    },
    {
        "name": "fundingSource",
        "baseName": "fundingSource",
        "type": "ApplePayDonations.FundingSourceEnum"
    },
    {
        "name": "recurringDetailReference",
        "baseName": "recurringDetailReference",
        "type": "string"
    },
    {
        "name": "storedPaymentMethodId",
        "baseName": "storedPaymentMethodId",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "ApplePayDonations.TypeEnum"
    }
];
(function (ApplePayDonations) {
    let FundingSourceEnum;
    (function (FundingSourceEnum) {
        FundingSourceEnum["Credit"] = "credit";
        FundingSourceEnum["Debit"] = "debit";
    })(FundingSourceEnum = ApplePayDonations.FundingSourceEnum || (ApplePayDonations.FundingSourceEnum = {}));
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["Applepay"] = "applepay";
    })(TypeEnum = ApplePayDonations.TypeEnum || (ApplePayDonations.TypeEnum = {}));
})(ApplePayDonations = exports.ApplePayDonations || (exports.ApplePayDonations = {}));
//# sourceMappingURL=applePayDonations.js.map