"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CashAppDetails = void 0;
class CashAppDetails {
    static getAttributeTypeMap() {
        return CashAppDetails.attributeTypeMap;
    }
}
exports.CashAppDetails = CashAppDetails;
CashAppDetails.discriminator = undefined;
CashAppDetails.attributeTypeMap = [
    {
        "name": "cashtag",
        "baseName": "cashtag",
        "type": "string"
    },
    {
        "name": "checkoutAttemptId",
        "baseName": "checkoutAttemptId",
        "type": "string"
    },
    {
        "name": "customerId",
        "baseName": "customerId",
        "type": "string"
    },
    {
        "name": "grantId",
        "baseName": "grantId",
        "type": "string"
    },
    {
        "name": "onFileGrantId",
        "baseName": "onFileGrantId",
        "type": "string"
    },
    {
        "name": "recurringDetailReference",
        "baseName": "recurringDetailReference",
        "type": "string"
    },
    {
        "name": "requestId",
        "baseName": "requestId",
        "type": "string"
    },
    {
        "name": "storedPaymentMethodId",
        "baseName": "storedPaymentMethodId",
        "type": "string"
    },
    {
        "name": "subtype",
        "baseName": "subtype",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "CashAppDetails.TypeEnum"
    }
];
(function (CashAppDetails) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["Cashapp"] = "cashapp";
    })(TypeEnum = CashAppDetails.TypeEnum || (CashAppDetails.TypeEnum = {}));
})(CashAppDetails = exports.CashAppDetails || (exports.CashAppDetails = {}));
//# sourceMappingURL=cashAppDetails.js.map