"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CheckoutBankAccount = void 0;
class CheckoutBankAccount {
    static getAttributeTypeMap() {
        return CheckoutBankAccount.attributeTypeMap;
    }
}
exports.CheckoutBankAccount = CheckoutBankAccount;
CheckoutBankAccount.discriminator = undefined;
CheckoutBankAccount.attributeTypeMap = [
    {
        "name": "accountType",
        "baseName": "accountType",
        "type": "CheckoutBankAccount.AccountTypeEnum"
    },
    {
        "name": "bankAccountNumber",
        "baseName": "bankAccountNumber",
        "type": "string"
    },
    {
        "name": "bankCity",
        "baseName": "bankCity",
        "type": "string"
    },
    {
        "name": "bankLocationId",
        "baseName": "bankLocationId",
        "type": "string"
    },
    {
        "name": "bankName",
        "baseName": "bankName",
        "type": "string"
    },
    {
        "name": "bic",
        "baseName": "bic",
        "type": "string"
    },
    {
        "name": "countryCode",
        "baseName": "countryCode",
        "type": "string"
    },
    {
        "name": "iban",
        "baseName": "iban",
        "type": "string"
    },
    {
        "name": "ownerName",
        "baseName": "ownerName",
        "type": "string"
    },
    {
        "name": "taxId",
        "baseName": "taxId",
        "type": "string"
    }
];
(function (CheckoutBankAccount) {
    let AccountTypeEnum;
    (function (AccountTypeEnum) {
        AccountTypeEnum["Balance"] = "balance";
        AccountTypeEnum["Checking"] = "checking";
        AccountTypeEnum["Deposit"] = "deposit";
        AccountTypeEnum["General"] = "general";
        AccountTypeEnum["Other"] = "other";
        AccountTypeEnum["Payment"] = "payment";
        AccountTypeEnum["Savings"] = "savings";
    })(AccountTypeEnum = CheckoutBankAccount.AccountTypeEnum || (CheckoutBankAccount.AccountTypeEnum = {}));
})(CheckoutBankAccount = exports.CheckoutBankAccount || (exports.CheckoutBankAccount = {}));
//# sourceMappingURL=checkoutBankAccount.js.map