"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CheckoutBankTransferAction = void 0;
class CheckoutBankTransferAction {
    static getAttributeTypeMap() {
        return CheckoutBankTransferAction.attributeTypeMap;
    }
}
exports.CheckoutBankTransferAction = CheckoutBankTransferAction;
CheckoutBankTransferAction.discriminator = undefined;
CheckoutBankTransferAction.attributeTypeMap = [
    {
        "name": "accountNumber",
        "baseName": "accountNumber",
        "type": "string"
    },
    {
        "name": "beneficiary",
        "baseName": "beneficiary",
        "type": "string"
    },
    {
        "name": "bic",
        "baseName": "bic",
        "type": "string"
    },
    {
        "name": "downloadUrl",
        "baseName": "downloadUrl",
        "type": "string"
    },
    {
        "name": "iban",
        "baseName": "iban",
        "type": "string"
    },
    {
        "name": "paymentMethodType",
        "baseName": "paymentMethodType",
        "type": "string"
    },
    {
        "name": "reference",
        "baseName": "reference",
        "type": "string"
    },
    {
        "name": "routingNumber",
        "baseName": "routingNumber",
        "type": "string"
    },
    {
        "name": "shopperEmail",
        "baseName": "shopperEmail",
        "type": "string"
    },
    {
        "name": "sortCode",
        "baseName": "sortCode",
        "type": "string"
    },
    {
        "name": "totalAmount",
        "baseName": "totalAmount",
        "type": "Amount | null"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "CheckoutBankTransferAction.TypeEnum"
    },
    {
        "name": "url",
        "baseName": "url",
        "type": "string"
    }
];
(function (CheckoutBankTransferAction) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["BankTransfer"] = "bankTransfer";
    })(TypeEnum = CheckoutBankTransferAction.TypeEnum || (CheckoutBankTransferAction.TypeEnum = {}));
})(CheckoutBankTransferAction = exports.CheckoutBankTransferAction || (exports.CheckoutBankTransferAction = {}));
//# sourceMappingURL=checkoutBankTransferAction.js.map