"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CheckoutSessionThreeDS2RequestData = void 0;
class CheckoutSessionThreeDS2RequestData {
    static getAttributeTypeMap() {
        return CheckoutSessionThreeDS2RequestData.attributeTypeMap;
    }
}
exports.CheckoutSessionThreeDS2RequestData = CheckoutSessionThreeDS2RequestData;
CheckoutSessionThreeDS2RequestData.discriminator = undefined;
CheckoutSessionThreeDS2RequestData.attributeTypeMap = [
    {
        "name": "homePhone",
        "baseName": "homePhone",
        "type": "Phone | null"
    },
    {
        "name": "mobilePhone",
        "baseName": "mobilePhone",
        "type": "Phone | null"
    },
    {
        "name": "threeDSRequestorChallengeInd",
        "baseName": "threeDSRequestorChallengeInd",
        "type": "CheckoutSessionThreeDS2RequestData.ThreeDSRequestorChallengeIndEnum"
    },
    {
        "name": "workPhone",
        "baseName": "workPhone",
        "type": "Phone | null"
    }
];
(function (CheckoutSessionThreeDS2RequestData) {
    let ThreeDSRequestorChallengeIndEnum;
    (function (ThreeDSRequestorChallengeIndEnum) {
        ThreeDSRequestorChallengeIndEnum["_01"] = "01";
        ThreeDSRequestorChallengeIndEnum["_02"] = "02";
        ThreeDSRequestorChallengeIndEnum["_03"] = "03";
        ThreeDSRequestorChallengeIndEnum["_04"] = "04";
        ThreeDSRequestorChallengeIndEnum["_05"] = "05";
        ThreeDSRequestorChallengeIndEnum["_06"] = "06";
    })(ThreeDSRequestorChallengeIndEnum = CheckoutSessionThreeDS2RequestData.ThreeDSRequestorChallengeIndEnum || (CheckoutSessionThreeDS2RequestData.ThreeDSRequestorChallengeIndEnum = {}));
})(CheckoutSessionThreeDS2RequestData = exports.CheckoutSessionThreeDS2RequestData || (exports.CheckoutSessionThreeDS2RequestData = {}));
//# sourceMappingURL=checkoutSessionThreeDS2RequestData.js.map