"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeliveryMethod = void 0;
class DeliveryMethod {
    static getAttributeTypeMap() {
        return DeliveryMethod.attributeTypeMap;
    }
}
exports.DeliveryMethod = DeliveryMethod;
DeliveryMethod.discriminator = undefined;
DeliveryMethod.attributeTypeMap = [
    {
        "name": "amount",
        "baseName": "amount",
        "type": "Amount | null"
    },
    {
        "name": "description",
        "baseName": "description",
        "type": "string"
    },
    {
        "name": "reference",
        "baseName": "reference",
        "type": "string"
    },
    {
        "name": "selected",
        "baseName": "selected",
        "type": "boolean"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "DeliveryMethod.TypeEnum"
    }
];
(function (DeliveryMethod) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["Shipping"] = "Shipping";
    })(TypeEnum = DeliveryMethod.TypeEnum || (DeliveryMethod.TypeEnum = {}));
})(DeliveryMethod = exports.DeliveryMethod || (exports.DeliveryMethod = {}));
//# sourceMappingURL=deliveryMethod.js.map