"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DonationCampaignsResponse = void 0;
class DonationCampaignsResponse {
    static getAttributeTypeMap() {
        return DonationCampaignsResponse.attributeTypeMap;
    }
}
exports.DonationCampaignsResponse = DonationCampaignsResponse;
DonationCampaignsResponse.discriminator = undefined;
DonationCampaignsResponse.attributeTypeMap = [
    {
        "name": "donationCampaigns",
        "baseName": "donationCampaigns",
        "type": "Array<DonationCampaign>"
    }
];
//# sourceMappingURL=donationCampaignsResponse.js.map