"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EBankingFinlandDetails = void 0;
class EBankingFinlandDetails {
    static getAttributeTypeMap() {
        return EBankingFinlandDetails.attributeTypeMap;
    }
}
exports.EBankingFinlandDetails = EBankingFinlandDetails;
EBankingFinlandDetails.discriminator = undefined;
EBankingFinlandDetails.attributeTypeMap = [
    {
        "name": "checkoutAttemptId",
        "baseName": "checkoutAttemptId",
        "type": "string"
    },
    {
        "name": "issuer",
        "baseName": "issuer",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "EBankingFinlandDetails.TypeEnum"
    }
];
(function (EBankingFinlandDetails) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["EbankingFi"] = "ebanking_FI";
    })(TypeEnum = EBankingFinlandDetails.TypeEnum || (EBankingFinlandDetails.TypeEnum = {}));
})(EBankingFinlandDetails = exports.EBankingFinlandDetails || (exports.EBankingFinlandDetails = {}));
//# sourceMappingURL=eBankingFinlandDetails.js.map