"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EnhancedSchemeData = void 0;
class EnhancedSchemeData {
    static getAttributeTypeMap() {
        return EnhancedSchemeData.attributeTypeMap;
    }
}
exports.EnhancedSchemeData = EnhancedSchemeData;
EnhancedSchemeData.discriminator = undefined;
EnhancedSchemeData.attributeTypeMap = [
    {
        "name": "airline",
        "baseName": "airline",
        "type": "Airline | null"
    }
];
//# sourceMappingURL=enhancedSchemeData.js.map