"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FastlaneDetails = void 0;
class FastlaneDetails {
    static getAttributeTypeMap() {
        return FastlaneDetails.attributeTypeMap;
    }
}
exports.FastlaneDetails = FastlaneDetails;
FastlaneDetails.discriminator = undefined;
FastlaneDetails.attributeTypeMap = [
    {
        "name": "checkoutAttemptId",
        "baseName": "checkoutAttemptId",
        "type": "string"
    },
    {
        "name": "fastlaneData",
        "baseName": "fastlaneData",
        "type": "string"
    },
    {
        "name": "recurringDetailReference",
        "baseName": "recurringDetailReference",
        "type": "string"
    },
    {
        "name": "storedPaymentMethodId",
        "baseName": "storedPaymentMethodId",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "FastlaneDetails.TypeEnum"
    }
];
(function (FastlaneDetails) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["Fastlane"] = "fastlane";
    })(TypeEnum = FastlaneDetails.TypeEnum || (FastlaneDetails.TypeEnum = {}));
})(FastlaneDetails = exports.FastlaneDetails || (exports.FastlaneDetails = {}));
//# sourceMappingURL=fastlaneDetails.js.map