"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GooglePayDonations = void 0;
class GooglePayDonations {
    static getAttributeTypeMap() {
        return GooglePayDonations.attributeTypeMap;
    }
}
exports.GooglePayDonations = GooglePayDonations;
GooglePayDonations.discriminator = undefined;
GooglePayDonations.attributeTypeMap = [
    {
        "name": "checkoutAttemptId",
        "baseName": "checkoutAttemptId",
        "type": "string"
    },
    {
        "name": "fundingSource",
        "baseName": "fundingSource",
        "type": "GooglePayDonations.FundingSourceEnum"
    },
    {
        "name": "googlePayCardNetwork",
        "baseName": "googlePayCardNetwork",
        "type": "string"
    },
    {
        "name": "googlePayToken",
        "baseName": "googlePayToken",
        "type": "string"
    },
    {
        "name": "recurringDetailReference",
        "baseName": "recurringDetailReference",
        "type": "string"
    },
    {
        "name": "storedPaymentMethodId",
        "baseName": "storedPaymentMethodId",
        "type": "string"
    },
    {
        "name": "threeDS2SdkVersion",
        "baseName": "threeDS2SdkVersion",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "GooglePayDonations.TypeEnum"
    }
];
(function (GooglePayDonations) {
    let FundingSourceEnum;
    (function (FundingSourceEnum) {
        FundingSourceEnum["Credit"] = "credit";
        FundingSourceEnum["Debit"] = "debit";
    })(FundingSourceEnum = GooglePayDonations.FundingSourceEnum || (GooglePayDonations.FundingSourceEnum = {}));
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["Googlepay"] = "googlepay";
    })(TypeEnum = GooglePayDonations.TypeEnum || (GooglePayDonations.TypeEnum = {}));
})(GooglePayDonations = exports.GooglePayDonations || (exports.GooglePayDonations = {}));
//# sourceMappingURL=googlePayDonations.js.map