"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IdealDonations = void 0;
class IdealDonations {
    static getAttributeTypeMap() {
        return IdealDonations.attributeTypeMap;
    }
}
exports.IdealDonations = IdealDonations;
IdealDonations.discriminator = undefined;
IdealDonations.attributeTypeMap = [
    {
        "name": "checkoutAttemptId",
        "baseName": "checkoutAttemptId",
        "type": "string"
    },
    {
        "name": "issuer",
        "baseName": "issuer",
        "type": "string"
    },
    {
        "name": "recurringDetailReference",
        "baseName": "recurringDetailReference",
        "type": "string"
    },
    {
        "name": "storedPaymentMethodId",
        "baseName": "storedPaymentMethodId",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "IdealDonations.TypeEnum"
    }
];
(function (IdealDonations) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["Ideal"] = "ideal";
    })(TypeEnum = IdealDonations.TypeEnum || (IdealDonations.TypeEnum = {}));
})(IdealDonations = exports.IdealDonations || (exports.IdealDonations = {}));
//# sourceMappingURL=idealDonations.js.map