"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Installments = void 0;
class Installments {
    static getAttributeTypeMap() {
        return Installments.attributeTypeMap;
    }
}
exports.Installments = Installments;
Installments.discriminator = undefined;
Installments.attributeTypeMap = [
    {
        "name": "extra",
        "baseName": "extra",
        "type": "number"
    },
    {
        "name": "plan",
        "baseName": "plan",
        "type": "Installments.PlanEnum"
    },
    {
        "name": "value",
        "baseName": "value",
        "type": "number"
    }
];
(function (Installments) {
    let PlanEnum;
    (function (PlanEnum) {
        PlanEnum["Bonus"] = "bonus";
        PlanEnum["BuynowPaylater"] = "buynow_paylater";
        PlanEnum["InteresRefundPrctg"] = "interes_refund_prctg";
        PlanEnum["InterestBonus"] = "interest_bonus";
        PlanEnum["NointeresRefundPrctg"] = "nointeres_refund_prctg";
        PlanEnum["NointerestBonus"] = "nointerest_bonus";
        PlanEnum["RefundPrctg"] = "refund_prctg";
        PlanEnum["Regular"] = "regular";
        PlanEnum["Revolving"] = "revolving";
        PlanEnum["WithInterest"] = "with_interest";
    })(PlanEnum = Installments.PlanEnum || (Installments.PlanEnum = {}));
})(Installments = exports.Installments || (exports.Installments = {}));
//# sourceMappingURL=installments.js.map