"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Passenger = void 0;
class Passenger {
    static getAttributeTypeMap() {
        return Passenger.attributeTypeMap;
    }
}
exports.Passenger = Passenger;
Passenger.discriminator = undefined;
Passenger.attributeTypeMap = [
    {
        "name": "dateOfBirth",
        "baseName": "dateOfBirth",
        "type": "string"
    },
    {
        "name": "firstName",
        "baseName": "firstName",
        "type": "string"
    },
    {
        "name": "lastName",
        "baseName": "lastName",
        "type": "string"
    },
    {
        "name": "phoneNumber",
        "baseName": "phoneNumber",
        "type": "string"
    },
    {
        "name": "travellerType",
        "baseName": "travellerType",
        "type": "string"
    }
];
//# sourceMappingURL=passenger.js.map