"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PayByBankAISDirectDebitDetails = void 0;
class PayByBankAISDirectDebitDetails {
    static getAttributeTypeMap() {
        return PayByBankAISDirectDebitDetails.attributeTypeMap;
    }
}
exports.PayByBankAISDirectDebitDetails = PayByBankAISDirectDebitDetails;
PayByBankAISDirectDebitDetails.discriminator = undefined;
PayByBankAISDirectDebitDetails.attributeTypeMap = [
    {
        "name": "checkoutAttemptId",
        "baseName": "checkoutAttemptId",
        "type": "string"
    },
    {
        "name": "recurringDetailReference",
        "baseName": "recurringDetailReference",
        "type": "string"
    },
    {
        "name": "storedPaymentMethodId",
        "baseName": "storedPaymentMethodId",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "PayByBankAISDirectDebitDetails.TypeEnum"
    }
];
(function (PayByBankAISDirectDebitDetails) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["PaybybankAisDd"] = "paybybank_AIS_DD";
    })(TypeEnum = PayByBankAISDirectDebitDetails.TypeEnum || (PayByBankAISDirectDebitDetails.TypeEnum = {}));
})(PayByBankAISDirectDebitDetails = exports.PayByBankAISDirectDebitDetails || (exports.PayByBankAISDirectDebitDetails = {}));
//# sourceMappingURL=payByBankAISDirectDebitDetails.js.map