"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PaymentMethodToStore = void 0;
class PaymentMethodToStore {
    static getAttributeTypeMap() {
        return PaymentMethodToStore.attributeTypeMap;
    }
}
exports.PaymentMethodToStore = PaymentMethodToStore;
PaymentMethodToStore.discriminator = undefined;
PaymentMethodToStore.attributeTypeMap = [
    {
        "name": "brand",
        "baseName": "brand",
        "type": "string"
    },
    {
        "name": "cvc",
        "baseName": "cvc",
        "type": "string"
    },
    {
        "name": "encryptedCard",
        "baseName": "encryptedCard",
        "type": "string"
    },
    {
        "name": "encryptedCardNumber",
        "baseName": "encryptedCardNumber",
        "type": "string"
    },
    {
        "name": "encryptedExpiryMonth",
        "baseName": "encryptedExpiryMonth",
        "type": "string"
    },
    {
        "name": "encryptedExpiryYear",
        "baseName": "encryptedExpiryYear",
        "type": "string"
    },
    {
        "name": "encryptedSecurityCode",
        "baseName": "encryptedSecurityCode",
        "type": "string"
    },
    {
        "name": "expiryMonth",
        "baseName": "expiryMonth",
        "type": "string"
    },
    {
        "name": "expiryYear",
        "baseName": "expiryYear",
        "type": "string"
    },
    {
        "name": "holderName",
        "baseName": "holderName",
        "type": "string"
    },
    {
        "name": "number",
        "baseName": "number",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    }
];
//# sourceMappingURL=paymentMethodToStore.js.map