"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PaymentMethodUPIApps = void 0;
class PaymentMethodUPIApps {
    static getAttributeTypeMap() {
        return PaymentMethodUPIApps.attributeTypeMap;
    }
}
exports.PaymentMethodUPIApps = PaymentMethodUPIApps;
PaymentMethodUPIApps.discriminator = undefined;
PaymentMethodUPIApps.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    }
];
//# sourceMappingURL=paymentMethodUPIApps.js.map