"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PayPayDetails = void 0;
class PayPayDetails {
    static getAttributeTypeMap() {
        return PayPayDetails.attributeTypeMap;
    }
}
exports.PayPayDetails = PayPayDetails;
PayPayDetails.discriminator = undefined;
PayPayDetails.attributeTypeMap = [
    {
        "name": "checkoutAttemptId",
        "baseName": "checkoutAttemptId",
        "type": "string"
    },
    {
        "name": "recurringDetailReference",
        "baseName": "recurringDetailReference",
        "type": "string"
    },
    {
        "name": "storedPaymentMethodId",
        "baseName": "storedPaymentMethodId",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "PayPayDetails.TypeEnum"
    }
];
(function (PayPayDetails) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["Paypay"] = "paypay";
    })(TypeEnum = PayPayDetails.TypeEnum || (PayPayDetails.TypeEnum = {}));
})(PayPayDetails = exports.PayPayDetails || (exports.PayPayDetails = {}));
//# sourceMappingURL=payPayDetails.js.map