"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PaypalUpdateOrderRequest = void 0;
class PaypalUpdateOrderRequest {
    static getAttributeTypeMap() {
        return PaypalUpdateOrderRequest.attributeTypeMap;
    }
}
exports.PaypalUpdateOrderRequest = PaypalUpdateOrderRequest;
PaypalUpdateOrderRequest.discriminator = undefined;
PaypalUpdateOrderRequest.attributeTypeMap = [
    {
        "name": "amount",
        "baseName": "amount",
        "type": "Amount | null"
    },
    {
        "name": "deliveryMethods",
        "baseName": "deliveryMethods",
        "type": "Array<DeliveryMethod>"
    },
    {
        "name": "paymentData",
        "baseName": "paymentData",
        "type": "string"
    },
    {
        "name": "pspReference",
        "baseName": "pspReference",
        "type": "string"
    },
    {
        "name": "sessionId",
        "baseName": "sessionId",
        "type": "string"
    },
    {
        "name": "taxTotal",
        "baseName": "taxTotal",
        "type": "TaxTotal | null"
    }
];
//# sourceMappingURL=paypalUpdateOrderRequest.js.map