"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PayWithGoogleDonations = void 0;
class PayWithGoogleDonations {
    static getAttributeTypeMap() {
        return PayWithGoogleDonations.attributeTypeMap;
    }
}
exports.PayWithGoogleDonations = PayWithGoogleDonations;
PayWithGoogleDonations.discriminator = undefined;
PayWithGoogleDonations.attributeTypeMap = [
    {
        "name": "checkoutAttemptId",
        "baseName": "checkoutAttemptId",
        "type": "string"
    },
    {
        "name": "fundingSource",
        "baseName": "fundingSource",
        "type": "PayWithGoogleDonations.FundingSourceEnum"
    },
    {
        "name": "googlePayToken",
        "baseName": "googlePayToken",
        "type": "string"
    },
    {
        "name": "recurringDetailReference",
        "baseName": "recurringDetailReference",
        "type": "string"
    },
    {
        "name": "storedPaymentMethodId",
        "baseName": "storedPaymentMethodId",
        "type": "string"
    },
    {
        "name": "threeDS2SdkVersion",
        "baseName": "threeDS2SdkVersion",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "PayWithGoogleDonations.TypeEnum"
    }
];
(function (PayWithGoogleDonations) {
    let FundingSourceEnum;
    (function (FundingSourceEnum) {
        FundingSourceEnum["Credit"] = "credit";
        FundingSourceEnum["Debit"] = "debit";
    })(FundingSourceEnum = PayWithGoogleDonations.FundingSourceEnum || (PayWithGoogleDonations.FundingSourceEnum = {}));
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["Paywithgoogle"] = "paywithgoogle";
    })(TypeEnum = PayWithGoogleDonations.TypeEnum || (PayWithGoogleDonations.TypeEnum = {}));
})(PayWithGoogleDonations = exports.PayWithGoogleDonations || (exports.PayWithGoogleDonations = {}));
//# sourceMappingURL=payWithGoogleDonations.js.map