"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PixDetails = void 0;
class PixDetails {
    static getAttributeTypeMap() {
        return PixDetails.attributeTypeMap;
    }
}
exports.PixDetails = PixDetails;
PixDetails.discriminator = undefined;
PixDetails.attributeTypeMap = [
    {
        "name": "checkoutAttemptId",
        "baseName": "checkoutAttemptId",
        "type": "string"
    },
    {
        "name": "pixRecurring",
        "baseName": "pixRecurring",
        "type": "PixRecurring | null"
    },
    {
        "name": "recurringDetailReference",
        "baseName": "recurringDetailReference",
        "type": "string"
    },
    {
        "name": "storedPaymentMethodId",
        "baseName": "storedPaymentMethodId",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "PixDetails.TypeEnum"
    }
];
(function (PixDetails) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["Pix"] = "pix";
    })(TypeEnum = PixDetails.TypeEnum || (PixDetails.TypeEnum = {}));
})(PixDetails = exports.PixDetails || (exports.PixDetails = {}));
//# sourceMappingURL=pixDetails.js.map