"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PixRecurring = void 0;
class PixRecurring {
    static getAttributeTypeMap() {
        return PixRecurring.attributeTypeMap;
    }
}
exports.PixRecurring = PixRecurring;
PixRecurring.discriminator = undefined;
PixRecurring.attributeTypeMap = [
    {
        "name": "billingDate",
        "baseName": "billingDate",
        "type": "string"
    },
    {
        "name": "endsAt",
        "baseName": "endsAt",
        "type": "string"
    },
    {
        "name": "frequency",
        "baseName": "frequency",
        "type": "PixRecurring.FrequencyEnum"
    },
    {
        "name": "minAmount",
        "baseName": "minAmount",
        "type": "Amount | null"
    },
    {
        "name": "originalPspReference",
        "baseName": "originalPspReference",
        "type": "string"
    },
    {
        "name": "recurringAmount",
        "baseName": "recurringAmount",
        "type": "Amount | null"
    },
    {
        "name": "recurringStatement",
        "baseName": "recurringStatement",
        "type": "string"
    },
    {
        "name": "retryPolicy",
        "baseName": "retryPolicy",
        "type": "boolean"
    },
    {
        "name": "startsAt",
        "baseName": "startsAt",
        "type": "string"
    }
];
(function (PixRecurring) {
    let FrequencyEnum;
    (function (FrequencyEnum) {
        FrequencyEnum["Weekly"] = "weekly";
        FrequencyEnum["Monthly"] = "monthly";
        FrequencyEnum["Quarterly"] = "quarterly";
        FrequencyEnum["HalfYearly"] = "half-yearly";
        FrequencyEnum["Yearly"] = "yearly";
    })(FrequencyEnum = PixRecurring.FrequencyEnum || (PixRecurring.FrequencyEnum = {}));
})(PixRecurring = exports.PixRecurring || (exports.PixRecurring = {}));
//# sourceMappingURL=pixRecurring.js.map