"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Split = void 0;
class Split {
    static getAttributeTypeMap() {
        return Split.attributeTypeMap;
    }
}
exports.Split = Split;
Split.discriminator = undefined;
Split.attributeTypeMap = [
    {
        "name": "account",
        "baseName": "account",
        "type": "string"
    },
    {
        "name": "amount",
        "baseName": "amount",
        "type": "SplitAmount | null"
    },
    {
        "name": "description",
        "baseName": "description",
        "type": "string"
    },
    {
        "name": "reference",
        "baseName": "reference",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "Split.TypeEnum"
    }
];
(function (Split) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["AcquiringFees"] = "AcquiringFees";
        TypeEnum["AdyenCommission"] = "AdyenCommission";
        TypeEnum["AdyenFees"] = "AdyenFees";
        TypeEnum["AdyenMarkup"] = "AdyenMarkup";
        TypeEnum["BalanceAccount"] = "BalanceAccount";
        TypeEnum["Commission"] = "Commission";
        TypeEnum["Default"] = "Default";
        TypeEnum["Interchange"] = "Interchange";
        TypeEnum["MarketPlace"] = "MarketPlace";
        TypeEnum["PaymentFee"] = "PaymentFee";
        TypeEnum["Remainder"] = "Remainder";
        TypeEnum["SchemeFee"] = "SchemeFee";
        TypeEnum["Surcharge"] = "Surcharge";
        TypeEnum["Tip"] = "Tip";
        TypeEnum["TopUp"] = "TopUp";
        TypeEnum["Vat"] = "VAT";
    })(TypeEnum = Split.TypeEnum || (Split.TypeEnum = {}));
})(Split = exports.Split || (exports.Split = {}));
//# sourceMappingURL=split.js.map