"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubMerchantInfo = void 0;
class SubMerchantInfo {
    static getAttributeTypeMap() {
        return SubMerchantInfo.attributeTypeMap;
    }
}
exports.SubMerchantInfo = SubMerchantInfo;
SubMerchantInfo.discriminator = undefined;
SubMerchantInfo.attributeTypeMap = [
    {
        "name": "address",
        "baseName": "address",
        "type": "BillingAddress | null"
    },
    {
        "name": "amount",
        "baseName": "amount",
        "type": "Amount | null"
    },
    {
        "name": "email",
        "baseName": "email",
        "type": "string"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "mcc",
        "baseName": "mcc",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "phoneNumber",
        "baseName": "phoneNumber",
        "type": "string"
    },
    {
        "name": "registeredSince",
        "baseName": "registeredSince",
        "type": "string"
    },
    {
        "name": "taxId",
        "baseName": "taxId",
        "type": "string"
    },
    {
        "name": "url",
        "baseName": "url",
        "type": "string"
    }
];
//# sourceMappingURL=subMerchantInfo.js.map