"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Ticket = void 0;
class Ticket {
    static getAttributeTypeMap() {
        return Ticket.attributeTypeMap;
    }
}
exports.Ticket = Ticket;
Ticket.discriminator = undefined;
Ticket.attributeTypeMap = [
    {
        "name": "issueAddress",
        "baseName": "issueAddress",
        "type": "string"
    },
    {
        "name": "issueDate",
        "baseName": "issueDate",
        "type": "string"
    },
    {
        "name": "number",
        "baseName": "number",
        "type": "string"
    }
];
//# sourceMappingURL=ticket.js.map