"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TravelAgency = void 0;
class TravelAgency {
    static getAttributeTypeMap() {
        return TravelAgency.attributeTypeMap;
    }
}
exports.TravelAgency = TravelAgency;
TravelAgency.discriminator = undefined;
TravelAgency.attributeTypeMap = [
    {
        "name": "code",
        "baseName": "code",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    }
];
//# sourceMappingURL=travelAgency.js.map