"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TwintDetails = void 0;
class TwintDetails {
    static getAttributeTypeMap() {
        return TwintDetails.attributeTypeMap;
    }
}
exports.TwintDetails = TwintDetails;
TwintDetails.discriminator = undefined;
TwintDetails.attributeTypeMap = [
    {
        "name": "checkoutAttemptId",
        "baseName": "checkoutAttemptId",
        "type": "string"
    },
    {
        "name": "recurringDetailReference",
        "baseName": "recurringDetailReference",
        "type": "string"
    },
    {
        "name": "storedPaymentMethodId",
        "baseName": "storedPaymentMethodId",
        "type": "string"
    },
    {
        "name": "subtype",
        "baseName": "subtype",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "TwintDetails.TypeEnum"
    }
];
(function (TwintDetails) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["Twint"] = "twint";
    })(TypeEnum = TwintDetails.TypeEnum || (TwintDetails.TypeEnum = {}));
})(TwintDetails = exports.TwintDetails || (exports.TwintDetails = {}));
//# sourceMappingURL=twintDetails.js.map