import { AccountHoldersApi } from "./accountHoldersApi";
import { BalanceAccountsApi } from "./balanceAccountsApi";
import { BankAccountValidationApi } from "./bankAccountValidationApi";
import { CardOrdersApi } from "./cardOrdersApi";
import { GrantAccountsApi } from "./grantAccountsApi";
import { GrantOffersApi } from "./grantOffersApi";
import { ManageCardPINApi } from "./manageCardPINApi";
import { ManageSCADevicesApi } from "./manageSCADevicesApi";
import { NetworkTokensApi } from "./networkTokensApi";
import { PaymentInstrumentGroupsApi } from "./paymentInstrumentGroupsApi";
import { PaymentInstrumentsApi } from "./paymentInstrumentsApi";
import { PlatformApi } from "./platformApi";
import { TransactionRulesApi } from "./transactionRulesApi";
import { TransferRoutesApi } from "./transferRoutesApi";
import Service from "../../service";
import Client from "../../client";
export default class BalancePlatformAPI extends Service {
    constructor(client: Client);
    get AccountHoldersApi(): AccountHoldersApi;
    get BalanceAccountsApi(): BalanceAccountsApi;
    get BankAccountValidationApi(): BankAccountValidationApi;
    get CardOrdersApi(): CardOrdersApi;
    get GrantAccountsApi(): GrantAccountsApi;
    get GrantOffersApi(): GrantOffersApi;
    get ManageCardPINApi(): ManageCardPINApi;
    get ManageSCADevicesApi(): ManageSCADevicesApi;
    get NetworkTokensApi(): NetworkTokensApi;
    get PaymentInstrumentGroupsApi(): PaymentInstrumentGroupsApi;
    get PaymentInstrumentsApi(): PaymentInstrumentsApi;
    get PlatformApi(): PlatformApi;
    get TransactionRulesApi(): TransactionRulesApi;
    get TransferRoutesApi(): TransferRoutesApi;
}
