"use strict";
/*
 * The version of the OpenAPI document: v71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.DonationsApi = void 0;
const getJsonResponse_1 = __importDefault(require("../../helpers/getJsonResponse"));
const service_1 = __importDefault(require("../../service"));
const models_1 = require("../../typings/checkout/models");
const resource_1 = __importDefault(require("../resource"));
class DonationsApi extends service_1.default {
    constructor(client) {
        super(client);
        this.API_BASEPATH = "https://checkout-test.adyen.com/v71";
        this.baseUrl = this.createBaseUrl(this.API_BASEPATH);
    }
    /**
    * @summary Get a list of donation campaigns.
    * @param donationCampaignsRequest {@link DonationCampaignsRequest }
    * @param requestOptions {@link IRequest.Options }
    * @return {@link DonationCampaignsResponse }
    */
    async donationCampaigns(donationCampaignsRequest, requestOptions) {
        const endpoint = `${this.baseUrl}/donationCampaigns`;
        const resource = new resource_1.default(this, endpoint);
        const request = models_1.ObjectSerializer.serialize(donationCampaignsRequest, "DonationCampaignsRequest");
        const response = await (0, getJsonResponse_1.default)(resource, request, { ...requestOptions, method: "POST" });
        return models_1.ObjectSerializer.deserialize(response, "DonationCampaignsResponse");
    }
    /**
    * @summary Start a transaction for donations
    * @param donationPaymentRequest {@link DonationPaymentRequest }
    * @param requestOptions {@link IRequest.Options }
    * @return {@link DonationPaymentResponse }
    */
    async donations(donationPaymentRequest, requestOptions) {
        const endpoint = `${this.baseUrl}/donations`;
        const resource = new resource_1.default(this, endpoint);
        const request = models_1.ObjectSerializer.serialize(donationPaymentRequest, "DonationPaymentRequest");
        const response = await (0, getJsonResponse_1.default)(resource, request, { ...requestOptions, method: "POST" });
        return models_1.ObjectSerializer.deserialize(response, "DonationPaymentResponse");
    }
}
exports.DonationsApi = DonationsApi;
//# sourceMappingURL=donationsApi.js.map