"use strict";
/*
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BalanceNotificationData = void 0;
class BalanceNotificationData {
    static getAttributeTypeMap() {
        return BalanceNotificationData.attributeTypeMap;
    }
}
exports.BalanceNotificationData = BalanceNotificationData;
BalanceNotificationData.discriminator = undefined;
BalanceNotificationData.attributeTypeMap = [
    {
        "name": "balanceAccountId",
        "baseName": "balanceAccountId",
        "type": "string"
    },
    {
        "name": "balancePlatform",
        "baseName": "balancePlatform",
        "type": "string"
    },
    {
        "name": "balances",
        "baseName": "balances",
        "type": "Balances"
    },
    {
        "name": "creationDate",
        "baseName": "creationDate",
        "type": "Date"
    },
    {
        "name": "currency",
        "baseName": "currency",
        "type": "string"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "settingIds",
        "baseName": "settingIds",
        "type": "Array<string>"
    }
];
//# sourceMappingURL=balanceNotificationData.js.map