"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AssociationDelegatedAuthenticationData = void 0;
class AssociationDelegatedAuthenticationData {
    static getAttributeTypeMap() {
        return AssociationDelegatedAuthenticationData.attributeTypeMap;
    }
}
exports.AssociationDelegatedAuthenticationData = AssociationDelegatedAuthenticationData;
AssociationDelegatedAuthenticationData.discriminator = undefined;
AssociationDelegatedAuthenticationData.attributeTypeMap = [
    {
        "name": "sdkOutput",
        "baseName": "sdkOutput",
        "type": "string"
    }
];
//# sourceMappingURL=associationDelegatedAuthenticationData.js.map