"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AssociationInitiateRequest = void 0;
class AssociationInitiateRequest {
    static getAttributeTypeMap() {
        return AssociationInitiateRequest.attributeTypeMap;
    }
}
exports.AssociationInitiateRequest = AssociationInitiateRequest;
AssociationInitiateRequest.discriminator = undefined;
AssociationInitiateRequest.attributeTypeMap = [
    {
        "name": "ids",
        "baseName": "ids",
        "type": "Array<string>"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "AssociationInitiateRequest.TypeEnum"
    }
];
(function (AssociationInitiateRequest) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["PaymentInstrument"] = "PaymentInstrument";
    })(TypeEnum = AssociationInitiateRequest.TypeEnum || (AssociationInitiateRequest.TypeEnum = {}));
})(AssociationInitiateRequest = exports.AssociationInitiateRequest || (exports.AssociationInitiateRequest = {}));
//# sourceMappingURL=associationInitiateRequest.js.map