"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AssociationFinaliseResponse = void 0;
class AssociationFinaliseResponse {
    static getAttributeTypeMap() {
        return AssociationFinaliseResponse.attributeTypeMap;
    }
}
exports.AssociationFinaliseResponse = AssociationFinaliseResponse;
AssociationFinaliseResponse.discriminator = undefined;
AssociationFinaliseResponse.attributeTypeMap = [
    {
        "name": "deviceId",
        "baseName": "deviceId",
        "type": "string"
    },
    {
        "name": "ids",
        "baseName": "ids",
        "type": "Array<string>"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "AssociationFinaliseResponse.TypeEnum"
    }
];
(function (AssociationFinaliseResponse) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["PaymentInstrument"] = "PAYMENT_INSTRUMENT";
    })(TypeEnum = AssociationFinaliseResponse.TypeEnum || (AssociationFinaliseResponse.TypeEnum = {}));
})(AssociationFinaliseResponse = exports.AssociationFinaliseResponse || (exports.AssociationFinaliseResponse = {}));
//# sourceMappingURL=associationFinaliseResponse.js.map