"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DelegatedAuthenticationData = void 0;
class DelegatedAuthenticationData {
    static getAttributeTypeMap() {
        return DelegatedAuthenticationData.attributeTypeMap;
    }
}
exports.DelegatedAuthenticationData = DelegatedAuthenticationData;
DelegatedAuthenticationData.discriminator = undefined;
DelegatedAuthenticationData.attributeTypeMap = [
    {
        "name": "sdkOutput",
        "baseName": "sdkOutput",
        "type": "string"
    }
];
//# sourceMappingURL=delegatedAuthenticationData.js.map