"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Href = void 0;
class Href {
    static getAttributeTypeMap() {
        return Href.attributeTypeMap;
    }
}
exports.Href = Href;
Href.discriminator = undefined;
Href.attributeTypeMap = [
    {
        "name": "href",
        "baseName": "href",
        "type": "string"
    }
];
//# sourceMappingURL=href.js.map