"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Link = void 0;
class Link {
    static getAttributeTypeMap() {
        return Link.attributeTypeMap;
    }
}
exports.Link = Link;
Link.discriminator = undefined;
Link.attributeTypeMap = [
    {
        "name": "first",
        "baseName": "first",
        "type": "Href | null"
    },
    {
        "name": "last",
        "baseName": "last",
        "type": "Href | null"
    },
    {
        "name": "next",
        "baseName": "next",
        "type": "Href | null"
    },
    {
        "name": "previous",
        "baseName": "previous",
        "type": "Href | null"
    },
    {
        "name": "self",
        "baseName": "self",
        "type": "Href | null"
    }
];
//# sourceMappingURL=link.js.map