"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PaymentInstrumentRevealResponse = void 0;
class PaymentInstrumentRevealResponse {
    static getAttributeTypeMap() {
        return PaymentInstrumentRevealResponse.attributeTypeMap;
    }
}
exports.PaymentInstrumentRevealResponse = PaymentInstrumentRevealResponse;
PaymentInstrumentRevealResponse.discriminator = undefined;
PaymentInstrumentRevealResponse.attributeTypeMap = [
    {
        "name": "encryptedData",
        "baseName": "encryptedData",
        "type": "string"
    }
];
//# sourceMappingURL=paymentInstrumentRevealResponse.js.map