"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PinChangeRequest = void 0;
class PinChangeRequest {
    static getAttributeTypeMap() {
        return PinChangeRequest.attributeTypeMap;
    }
}
exports.PinChangeRequest = PinChangeRequest;
PinChangeRequest.discriminator = undefined;
PinChangeRequest.attributeTypeMap = [
    {
        "name": "encryptedKey",
        "baseName": "encryptedKey",
        "type": "string"
    },
    {
        "name": "encryptedPinBlock",
        "baseName": "encryptedPinBlock",
        "type": "string"
    },
    {
        "name": "paymentInstrumentId",
        "baseName": "paymentInstrumentId",
        "type": "string"
    },
    {
        "name": "token",
        "baseName": "token",
        "type": "string"
    }
];
//# sourceMappingURL=pinChangeRequest.js.map