"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PublicKeyResponse = void 0;
class PublicKeyResponse {
    static getAttributeTypeMap() {
        return PublicKeyResponse.attributeTypeMap;
    }
}
exports.PublicKeyResponse = PublicKeyResponse;
PublicKeyResponse.discriminator = undefined;
PublicKeyResponse.attributeTypeMap = [
    {
        "name": "publicKey",
        "baseName": "publicKey",
        "type": "string"
    },
    {
        "name": "publicKeyExpiryDate",
        "baseName": "publicKeyExpiryDate",
        "type": "string"
    }
];
//# sourceMappingURL=publicKeyResponse.js.map