"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RegisterSCARequest = void 0;
class RegisterSCARequest {
    static getAttributeTypeMap() {
        return RegisterSCARequest.attributeTypeMap;
    }
}
exports.RegisterSCARequest = RegisterSCARequest;
RegisterSCARequest.discriminator = undefined;
RegisterSCARequest.attributeTypeMap = [
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "paymentInstrumentId",
        "baseName": "paymentInstrumentId",
        "type": "string"
    },
    {
        "name": "strongCustomerAuthentication",
        "baseName": "strongCustomerAuthentication",
        "type": "DelegatedAuthenticationData"
    }
];
//# sourceMappingURL=registerSCARequest.js.map