"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RegisterSCAFinalResponse = void 0;
class RegisterSCAFinalResponse {
    static getAttributeTypeMap() {
        return RegisterSCAFinalResponse.attributeTypeMap;
    }
}
exports.RegisterSCAFinalResponse = RegisterSCAFinalResponse;
RegisterSCAFinalResponse.discriminator = undefined;
RegisterSCAFinalResponse.attributeTypeMap = [
    {
        "name": "success",
        "baseName": "success",
        "type": "boolean"
    }
];
//# sourceMappingURL=registerSCAFinalResponse.js.map