"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RegisterSCAResponse = void 0;
class RegisterSCAResponse {
    static getAttributeTypeMap() {
        return RegisterSCAResponse.attributeTypeMap;
    }
}
exports.RegisterSCAResponse = RegisterSCAResponse;
RegisterSCAResponse.discriminator = undefined;
RegisterSCAResponse.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "paymentInstrumentId",
        "baseName": "paymentInstrumentId",
        "type": "string"
    },
    {
        "name": "sdkInput",
        "baseName": "sdkInput",
        "type": "string"
    },
    {
        "name": "success",
        "baseName": "success",
        "type": "boolean"
    }
];
//# sourceMappingURL=registerSCAResponse.js.map