"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RevealPinRequest = void 0;
class RevealPinRequest {
    static getAttributeTypeMap() {
        return RevealPinRequest.attributeTypeMap;
    }
}
exports.RevealPinRequest = RevealPinRequest;
RevealPinRequest.discriminator = undefined;
RevealPinRequest.attributeTypeMap = [
    {
        "name": "encryptedKey",
        "baseName": "encryptedKey",
        "type": "string"
    },
    {
        "name": "paymentInstrumentId",
        "baseName": "paymentInstrumentId",
        "type": "string"
    }
];
//# sourceMappingURL=revealPinRequest.js.map