"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RevealPinResponse = void 0;
class RevealPinResponse {
    static getAttributeTypeMap() {
        return RevealPinResponse.attributeTypeMap;
    }
}
exports.RevealPinResponse = RevealPinResponse;
RevealPinResponse.discriminator = undefined;
RevealPinResponse.attributeTypeMap = [
    {
        "name": "encryptedPinBlock",
        "baseName": "encryptedPinBlock",
        "type": "string"
    },
    {
        "name": "token",
        "baseName": "token",
        "type": "string"
    }
];
//# sourceMappingURL=revealPinResponse.js.map