"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RiskScores = void 0;
class RiskScores {
    static getAttributeTypeMap() {
        return RiskScores.attributeTypeMap;
    }
}
exports.RiskScores = RiskScores;
RiskScores.discriminator = undefined;
RiskScores.attributeTypeMap = [
    {
        "name": "mastercard",
        "baseName": "mastercard",
        "type": "number"
    },
    {
        "name": "visa",
        "baseName": "visa",
        "type": "number"
    }
];
//# sourceMappingURL=riskScores.js.map