"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RiskScoresRestriction = void 0;
class RiskScoresRestriction {
    static getAttributeTypeMap() {
        return RiskScoresRestriction.attributeTypeMap;
    }
}
exports.RiskScoresRestriction = RiskScoresRestriction;
RiskScoresRestriction.discriminator = undefined;
RiskScoresRestriction.attributeTypeMap = [
    {
        "name": "operation",
        "baseName": "operation",
        "type": "string"
    },
    {
        "name": "value",
        "baseName": "value",
        "type": "RiskScores | null"
    }
];
//# sourceMappingURL=riskScoresRestriction.js.map