"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SourceAccountTypesRestriction = void 0;
class SourceAccountTypesRestriction {
    static getAttributeTypeMap() {
        return SourceAccountTypesRestriction.attributeTypeMap;
    }
}
exports.SourceAccountTypesRestriction = SourceAccountTypesRestriction;
SourceAccountTypesRestriction.discriminator = undefined;
SourceAccountTypesRestriction.attributeTypeMap = [
    {
        "name": "operation",
        "baseName": "operation",
        "type": "string"
    },
    {
        "name": "value",
        "baseName": "value",
        "type": "Array<SourceAccountTypesRestriction.ValueEnum>"
    }
];
(function (SourceAccountTypesRestriction) {
    let ValueEnum;
    (function (ValueEnum) {
        ValueEnum["BalanceAccount"] = "balanceAccount";
        ValueEnum["BusinessAccount"] = "businessAccount";
    })(ValueEnum = SourceAccountTypesRestriction.ValueEnum || (SourceAccountTypesRestriction.ValueEnum = {}));
})(SourceAccountTypesRestriction = exports.SourceAccountTypesRestriction || (exports.SourceAccountTypesRestriction = {}));
//# sourceMappingURL=sourceAccountTypesRestriction.js.map