"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.USInternationalAchAddressRequirement = void 0;
class USInternationalAchAddressRequirement {
    static getAttributeTypeMap() {
        return USInternationalAchAddressRequirement.attributeTypeMap;
    }
}
exports.USInternationalAchAddressRequirement = USInternationalAchAddressRequirement;
USInternationalAchAddressRequirement.discriminator = undefined;
USInternationalAchAddressRequirement.attributeTypeMap = [
    {
        "name": "description",
        "baseName": "description",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "USInternationalAchAddressRequirement.TypeEnum"
    }
];
(function (USInternationalAchAddressRequirement) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["UsInternationalAchAddressRequirement"] = "usInternationalAchAddressRequirement";
    })(TypeEnum = USInternationalAchAddressRequirement.TypeEnum || (USInternationalAchAddressRequirement.TypeEnum = {}));
})(USInternationalAchAddressRequirement = exports.USInternationalAchAddressRequirement || (exports.USInternationalAchAddressRequirement = {}));
//# sourceMappingURL=uSInternationalAchAddressRequirement.js.map