"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.USInstantPayoutAddressRequirement = void 0;
class USInstantPayoutAddressRequirement {
    static getAttributeTypeMap() {
        return USInstantPayoutAddressRequirement.attributeTypeMap;
    }
}
exports.USInstantPayoutAddressRequirement = USInstantPayoutAddressRequirement;
USInstantPayoutAddressRequirement.discriminator = undefined;
USInstantPayoutAddressRequirement.attributeTypeMap = [
    {
        "name": "description",
        "baseName": "description",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "USInstantPayoutAddressRequirement.TypeEnum"
    }
];
(function (USInstantPayoutAddressRequirement) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["UsInstantPayoutAddressRequirement"] = "usInstantPayoutAddressRequirement";
    })(TypeEnum = USInstantPayoutAddressRequirement.TypeEnum || (USInstantPayoutAddressRequirement.TypeEnum = {}));
})(USInstantPayoutAddressRequirement = exports.USInstantPayoutAddressRequirement || (exports.USInstantPayoutAddressRequirement = {}));
//# sourceMappingURL=uSInstantPayoutAddressRequirement.js.map