"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffirmInfo = void 0;
class AffirmInfo {
    static getAttributeTypeMap() {
        return AffirmInfo.attributeTypeMap;
    }
}
exports.AffirmInfo = AffirmInfo;
AffirmInfo.discriminator = undefined;
AffirmInfo.attributeTypeMap = [
    {
        "name": "supportEmail",
        "baseName": "supportEmail",
        "type": "string"
    }
];
//# sourceMappingURL=affirmInfo.js.map