"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AndroidAppError = void 0;
class AndroidAppError {
    static getAttributeTypeMap() {
        return AndroidAppError.attributeTypeMap;
    }
}
exports.AndroidAppError = AndroidAppError;
AndroidAppError.discriminator = undefined;
AndroidAppError.attributeTypeMap = [
    {
        "name": "errorCode",
        "baseName": "errorCode",
        "type": "string"
    },
    {
        "name": "terminalModels",
        "baseName": "terminalModels",
        "type": "Array<string>"
    }
];
//# sourceMappingURL=androidAppError.js.map