"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AndroidApp = void 0;
class AndroidApp {
    static getAttributeTypeMap() {
        return AndroidApp.attributeTypeMap;
    }
}
exports.AndroidApp = AndroidApp;
AndroidApp.discriminator = undefined;
AndroidApp.attributeTypeMap = [
    {
        "name": "description",
        "baseName": "description",
        "type": "string"
    },
    {
        "name": "errorCode",
        "baseName": "errorCode",
        "type": "string"
    },
    {
        "name": "errors",
        "baseName": "errors",
        "type": "Array<AndroidAppError>"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "label",
        "baseName": "label",
        "type": "string"
    },
    {
        "name": "packageName",
        "baseName": "packageName",
        "type": "string"
    },
    {
        "name": "status",
        "baseName": "status",
        "type": "AndroidApp.StatusEnum"
    },
    {
        "name": "versionCode",
        "baseName": "versionCode",
        "type": "number"
    },
    {
        "name": "versionName",
        "baseName": "versionName",
        "type": "string"
    }
];
(function (AndroidApp) {
    let StatusEnum;
    (function (StatusEnum) {
        StatusEnum["Archived"] = "archived";
        StatusEnum["Error"] = "error";
        StatusEnum["Invalid"] = "invalid";
        StatusEnum["Processing"] = "processing";
        StatusEnum["Ready"] = "ready";
    })(StatusEnum = AndroidApp.StatusEnum || (AndroidApp.StatusEnum = {}));
})(AndroidApp = exports.AndroidApp || (exports.AndroidApp = {}));
//# sourceMappingURL=androidApp.js.map