"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiCredentialLinks = void 0;
class ApiCredentialLinks {
    static getAttributeTypeMap() {
        return ApiCredentialLinks.attributeTypeMap;
    }
}
exports.ApiCredentialLinks = ApiCredentialLinks;
ApiCredentialLinks.discriminator = undefined;
ApiCredentialLinks.attributeTypeMap = [
    {
        "name": "allowedOrigins",
        "baseName": "allowedOrigins",
        "type": "LinksElement | null"
    },
    {
        "name": "company",
        "baseName": "company",
        "type": "LinksElement | null"
    },
    {
        "name": "generateApiKey",
        "baseName": "generateApiKey",
        "type": "LinksElement | null"
    },
    {
        "name": "generateClientKey",
        "baseName": "generateClientKey",
        "type": "LinksElement | null"
    },
    {
        "name": "merchant",
        "baseName": "merchant",
        "type": "LinksElement | null"
    },
    {
        "name": "self",
        "baseName": "self",
        "type": "LinksElement"
    }
];
//# sourceMappingURL=apiCredentialLinks.js.map