"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CompanyLinks = void 0;
class CompanyLinks {
    static getAttributeTypeMap() {
        return CompanyLinks.attributeTypeMap;
    }
}
exports.CompanyLinks = CompanyLinks;
CompanyLinks.discriminator = undefined;
CompanyLinks.attributeTypeMap = [
    {
        "name": "apiCredentials",
        "baseName": "apiCredentials",
        "type": "LinksElement | null"
    },
    {
        "name": "self",
        "baseName": "self",
        "type": "LinksElement"
    },
    {
        "name": "users",
        "baseName": "users",
        "type": "LinksElement | null"
    },
    {
        "name": "webhooks",
        "baseName": "webhooks",
        "type": "LinksElement | null"
    }
];
//# sourceMappingURL=companyLinks.js.map