"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DinersInfo = void 0;
class DinersInfo {
    static getAttributeTypeMap() {
        return DinersInfo.attributeTypeMap;
    }
}
exports.DinersInfo = DinersInfo;
DinersInfo.discriminator = undefined;
DinersInfo.attributeTypeMap = [
    {
        "name": "midNumber",
        "baseName": "midNumber",
        "type": "string"
    },
    {
        "name": "reuseMidNumber",
        "baseName": "reuseMidNumber",
        "type": "boolean"
    },
    {
        "name": "serviceLevel",
        "baseName": "serviceLevel",
        "type": "DinersInfo.ServiceLevelEnum"
    },
    {
        "name": "transactionDescription",
        "baseName": "transactionDescription",
        "type": "TransactionDescriptionInfo | null"
    }
];
(function (DinersInfo) {
    let ServiceLevelEnum;
    (function (ServiceLevelEnum) {
        ServiceLevelEnum["NoContract"] = "noContract";
        ServiceLevelEnum["GatewayContract"] = "gatewayContract";
    })(ServiceLevelEnum = DinersInfo.ServiceLevelEnum || (DinersInfo.ServiceLevelEnum = {}));
})(DinersInfo = exports.DinersInfo || (exports.DinersInfo = {}));
//# sourceMappingURL=dinersInfo.js.map