"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PaymentMethod = void 0;
class PaymentMethod {
    static getAttributeTypeMap() {
        return PaymentMethod.attributeTypeMap;
    }
}
exports.PaymentMethod = PaymentMethod;
PaymentMethod.discriminator = undefined;
PaymentMethod.attributeTypeMap = [
    {
        "name": "accel",
        "baseName": "accel",
        "type": "AccelInfo | null"
    },
    {
        "name": "affirm",
        "baseName": "affirm",
        "type": "AffirmInfo | null"
    },
    {
        "name": "afterpayTouch",
        "baseName": "afterpayTouch",
        "type": "AfterpayTouchInfo | null"
    },
    {
        "name": "allowed",
        "baseName": "allowed",
        "type": "boolean"
    },
    {
        "name": "amex",
        "baseName": "amex",
        "type": "AmexInfo | null"
    },
    {
        "name": "applePay",
        "baseName": "applePay",
        "type": "ApplePayInfo | null"
    },
    {
        "name": "bcmc",
        "baseName": "bcmc",
        "type": "BcmcInfo | null"
    },
    {
        "name": "businessLineId",
        "baseName": "businessLineId",
        "type": "string"
    },
    {
        "name": "cartesBancaires",
        "baseName": "cartesBancaires",
        "type": "CartesBancairesInfo | null"
    },
    {
        "name": "clearpay",
        "baseName": "clearpay",
        "type": "ClearpayInfo | null"
    },
    {
        "name": "countries",
        "baseName": "countries",
        "type": "Array<string>"
    },
    {
        "name": "cup",
        "baseName": "cup",
        "type": "GenericPmWithTdiInfo | null"
    },
    {
        "name": "currencies",
        "baseName": "currencies",
        "type": "Array<string>"
    },
    {
        "name": "customRoutingFlags",
        "baseName": "customRoutingFlags",
        "type": "Array<string>"
    },
    {
        "name": "diners",
        "baseName": "diners",
        "type": "DinersInfo | null"
    },
    {
        "name": "discover",
        "baseName": "discover",
        "type": "GenericPmWithTdiInfo | null"
    },
    {
        "name": "eft_directdebit_CA",
        "baseName": "eft_directdebit_CA",
        "type": "GenericPmWithTdiInfo | null"
    },
    {
        "name": "eftpos_australia",
        "baseName": "eftpos_australia",
        "type": "GenericPmWithTdiInfo | null"
    },
    {
        "name": "enabled",
        "baseName": "enabled",
        "type": "boolean"
    },
    {
        "name": "girocard",
        "baseName": "girocard",
        "type": "GenericPmWithTdiInfo | null"
    },
    {
        "name": "googlePay",
        "baseName": "googlePay",
        "type": "GooglePayInfo | null"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "ideal",
        "baseName": "ideal",
        "type": "GenericPmWithTdiInfo | null"
    },
    {
        "name": "interac_card",
        "baseName": "interac_card",
        "type": "GenericPmWithTdiInfo | null"
    },
    {
        "name": "jcb",
        "baseName": "jcb",
        "type": "JCBInfo | null"
    },
    {
        "name": "klarna",
        "baseName": "klarna",
        "type": "KlarnaInfo | null"
    },
    {
        "name": "maestro",
        "baseName": "maestro",
        "type": "GenericPmWithTdiInfo | null"
    },
    {
        "name": "mc",
        "baseName": "mc",
        "type": "GenericPmWithTdiInfo | null"
    },
    {
        "name": "mealVoucher_FR",
        "baseName": "mealVoucher_FR",
        "type": "MealVoucherFRInfo | null"
    },
    {
        "name": "nyce",
        "baseName": "nyce",
        "type": "NyceInfo | null"
    },
    {
        "name": "paybybank_plaid",
        "baseName": "paybybank_plaid",
        "type": "PayByBankPlaidInfo | null"
    },
    {
        "name": "payme",
        "baseName": "payme",
        "type": "PayMeInfo | null"
    },
    {
        "name": "paypal",
        "baseName": "paypal",
        "type": "PayPalInfo | null"
    },
    {
        "name": "payto",
        "baseName": "payto",
        "type": "PayToInfo | null"
    },
    {
        "name": "pulse",
        "baseName": "pulse",
        "type": "PulseInfo | null"
    },
    {
        "name": "reference",
        "baseName": "reference",
        "type": "string"
    },
    {
        "name": "shopperInteraction",
        "baseName": "shopperInteraction",
        "type": "string"
    },
    {
        "name": "sodexo",
        "baseName": "sodexo",
        "type": "SodexoInfo | null"
    },
    {
        "name": "sofort",
        "baseName": "sofort",
        "type": "SofortInfo | null"
    },
    {
        "name": "star",
        "baseName": "star",
        "type": "StarInfo | null"
    },
    {
        "name": "storeIds",
        "baseName": "storeIds",
        "type": "Array<string>"
    },
    {
        "name": "swish",
        "baseName": "swish",
        "type": "SwishInfo | null"
    },
    {
        "name": "ticket",
        "baseName": "ticket",
        "type": "TicketInfo | null"
    },
    {
        "name": "twint",
        "baseName": "twint",
        "type": "TwintInfo | null"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    },
    {
        "name": "verificationStatus",
        "baseName": "verificationStatus",
        "type": "PaymentMethod.VerificationStatusEnum"
    },
    {
        "name": "vipps",
        "baseName": "vipps",
        "type": "VippsInfo | null"
    },
    {
        "name": "visa",
        "baseName": "visa",
        "type": "GenericPmWithTdiInfo | null"
    },
    {
        "name": "wechatpay",
        "baseName": "wechatpay",
        "type": "WeChatPayInfo | null"
    },
    {
        "name": "wechatpay_pos",
        "baseName": "wechatpay_pos",
        "type": "WeChatPayPosInfo | null"
    }
];
(function (PaymentMethod) {
    let VerificationStatusEnum;
    (function (VerificationStatusEnum) {
        VerificationStatusEnum["Valid"] = "valid";
        VerificationStatusEnum["Pending"] = "pending";
        VerificationStatusEnum["Invalid"] = "invalid";
        VerificationStatusEnum["Rejected"] = "rejected";
    })(VerificationStatusEnum = PaymentMethod.VerificationStatusEnum || (PaymentMethod.VerificationStatusEnum = {}));
})(PaymentMethod = exports.PaymentMethod || (exports.PaymentMethod = {}));
//# sourceMappingURL=paymentMethod.js.map