"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PulseInfo = void 0;
class PulseInfo {
    static getAttributeTypeMap() {
        return PulseInfo.attributeTypeMap;
    }
}
exports.PulseInfo = PulseInfo;
PulseInfo.discriminator = undefined;
PulseInfo.attributeTypeMap = [
    {
        "name": "processingType",
        "baseName": "processingType",
        "type": "PulseInfo.ProcessingTypeEnum"
    },
    {
        "name": "transactionDescription",
        "baseName": "transactionDescription",
        "type": "TransactionDescriptionInfo | null"
    }
];
(function (PulseInfo) {
    let ProcessingTypeEnum;
    (function (ProcessingTypeEnum) {
        ProcessingTypeEnum["Billpay"] = "billpay";
        ProcessingTypeEnum["Ecom"] = "ecom";
        ProcessingTypeEnum["Pos"] = "pos";
    })(ProcessingTypeEnum = PulseInfo.ProcessingTypeEnum || (PulseInfo.ProcessingTypeEnum = {}));
})(PulseInfo = exports.PulseInfo || (exports.PulseInfo = {}));
//# sourceMappingURL=pulseInfo.js.map