"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Referenced = void 0;
class Referenced {
    static getAttributeTypeMap() {
        return Referenced.attributeTypeMap;
    }
}
exports.Referenced = Referenced;
Referenced.discriminator = undefined;
Referenced.attributeTypeMap = [
    {
        "name": "enableStandaloneRefunds",
        "baseName": "enableStandaloneRefunds",
        "type": "boolean"
    }
];
//# sourceMappingURL=referenced.js.map