"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.StarInfo = void 0;
class StarInfo {
    static getAttributeTypeMap() {
        return StarInfo.attributeTypeMap;
    }
}
exports.StarInfo = StarInfo;
StarInfo.discriminator = undefined;
StarInfo.attributeTypeMap = [
    {
        "name": "processingType",
        "baseName": "processingType",
        "type": "StarInfo.ProcessingTypeEnum"
    },
    {
        "name": "transactionDescription",
        "baseName": "transactionDescription",
        "type": "TransactionDescriptionInfo | null"
    }
];
(function (StarInfo) {
    let ProcessingTypeEnum;
    (function (ProcessingTypeEnum) {
        ProcessingTypeEnum["Billpay"] = "billpay";
        ProcessingTypeEnum["Ecom"] = "ecom";
        ProcessingTypeEnum["Pos"] = "pos";
    })(ProcessingTypeEnum = StarInfo.ProcessingTypeEnum || (StarInfo.ProcessingTypeEnum = {}));
})(StarInfo = exports.StarInfo || (exports.StarInfo = {}));
//# sourceMappingURL=starInfo.js.map