"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SupportedCardTypes = void 0;
class SupportedCardTypes {
    static getAttributeTypeMap() {
        return SupportedCardTypes.attributeTypeMap;
    }
}
exports.SupportedCardTypes = SupportedCardTypes;
SupportedCardTypes.discriminator = undefined;
SupportedCardTypes.attributeTypeMap = [
    {
        "name": "credit",
        "baseName": "credit",
        "type": "boolean"
    },
    {
        "name": "debit",
        "baseName": "debit",
        "type": "boolean"
    },
    {
        "name": "deferredDebit",
        "baseName": "deferredDebit",
        "type": "boolean"
    },
    {
        "name": "prepaid",
        "baseName": "prepaid",
        "type": "boolean"
    },
    {
        "name": "unknown",
        "baseName": "unknown",
        "type": "boolean"
    }
];
//# sourceMappingURL=supportedCardTypes.js.map