"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TapToPay = void 0;
class TapToPay {
    static getAttributeTypeMap() {
        return TapToPay.attributeTypeMap;
    }
}
exports.TapToPay = TapToPay;
TapToPay.discriminator = undefined;
TapToPay.attributeTypeMap = [
    {
        "name": "merchantDisplayName",
        "baseName": "merchantDisplayName",
        "type": "string"
    }
];
//# sourceMappingURL=tapToPay.js.map