"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TerminalSettings = void 0;
class TerminalSettings {
    static getAttributeTypeMap() {
        return TerminalSettings.attributeTypeMap;
    }
}
exports.TerminalSettings = TerminalSettings;
TerminalSettings.discriminator = undefined;
TerminalSettings.attributeTypeMap = [
    {
        "name": "cardholderReceipt",
        "baseName": "cardholderReceipt",
        "type": "CardholderReceipt | null"
    },
    {
        "name": "connectivity",
        "baseName": "connectivity",
        "type": "Connectivity | null"
    },
    {
        "name": "gratuities",
        "baseName": "gratuities",
        "type": "Array<Gratuity> | null"
    },
    {
        "name": "hardware",
        "baseName": "hardware",
        "type": "Hardware | null"
    },
    {
        "name": "localization",
        "baseName": "localization",
        "type": "Localization | null"
    },
    {
        "name": "nexo",
        "baseName": "nexo",
        "type": "Nexo | null"
    },
    {
        "name": "offlineProcessing",
        "baseName": "offlineProcessing",
        "type": "OfflineProcessing | null"
    },
    {
        "name": "opi",
        "baseName": "opi",
        "type": "Opi | null"
    },
    {
        "name": "passcodes",
        "baseName": "passcodes",
        "type": "Passcodes | null"
    },
    {
        "name": "payAtTable",
        "baseName": "payAtTable",
        "type": "PayAtTable | null"
    },
    {
        "name": "payment",
        "baseName": "payment",
        "type": "Payment | null"
    },
    {
        "name": "receiptOptions",
        "baseName": "receiptOptions",
        "type": "ReceiptOptions | null"
    },
    {
        "name": "receiptPrinting",
        "baseName": "receiptPrinting",
        "type": "ReceiptPrinting | null"
    },
    {
        "name": "refunds",
        "baseName": "refunds",
        "type": "Refunds | null"
    },
    {
        "name": "signature",
        "baseName": "signature",
        "type": "Signature | null"
    },
    {
        "name": "standalone",
        "baseName": "standalone",
        "type": "Standalone | null"
    },
    {
        "name": "storeAndForward",
        "baseName": "storeAndForward",
        "type": "StoreAndForward | null"
    },
    {
        "name": "surcharge",
        "baseName": "surcharge",
        "type": "Surcharge | null"
    },
    {
        "name": "tapToPay",
        "baseName": "tapToPay",
        "type": "TapToPay | null"
    },
    {
        "name": "terminalInstructions",
        "baseName": "terminalInstructions",
        "type": "TerminalInstructions | null"
    },
    {
        "name": "timeouts",
        "baseName": "timeouts",
        "type": "Timeouts | null"
    },
    {
        "name": "wifiProfiles",
        "baseName": "wifiProfiles",
        "type": "WifiProfiles | null"
    }
];
//# sourceMappingURL=terminalSettings.js.map