"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TicketInfo = void 0;
class TicketInfo {
    static getAttributeTypeMap() {
        return TicketInfo.attributeTypeMap;
    }
}
exports.TicketInfo = TicketInfo;
TicketInfo.discriminator = undefined;
TicketInfo.attributeTypeMap = [
    {
        "name": "requestorId",
        "baseName": "requestorId",
        "type": "string"
    }
];
//# sourceMappingURL=ticketInfo.js.map