"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UploadAndroidCertificateResponse = void 0;
class UploadAndroidCertificateResponse {
    static getAttributeTypeMap() {
        return UploadAndroidCertificateResponse.attributeTypeMap;
    }
}
exports.UploadAndroidCertificateResponse = UploadAndroidCertificateResponse;
UploadAndroidCertificateResponse.discriminator = undefined;
UploadAndroidCertificateResponse.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    }
];
//# sourceMappingURL=uploadAndroidCertificateResponse.js.map