"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WeChatPayInfo = void 0;
class WeChatPayInfo {
    static getAttributeTypeMap() {
        return WeChatPayInfo.attributeTypeMap;
    }
}
exports.WeChatPayInfo = WeChatPayInfo;
WeChatPayInfo.discriminator = undefined;
WeChatPayInfo.attributeTypeMap = [
    {
        "name": "contactPersonName",
        "baseName": "contactPersonName",
        "type": "string"
    },
    {
        "name": "email",
        "baseName": "email",
        "type": "string"
    }
];
//# sourceMappingURL=weChatPayInfo.js.map