"use strict";
/*
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DisputeNotificationRequest = void 0;
class DisputeNotificationRequest {
    static getAttributeTypeMap() {
        return DisputeNotificationRequest.attributeTypeMap;
    }
}
exports.DisputeNotificationRequest = DisputeNotificationRequest;
DisputeNotificationRequest.discriminator = undefined;
DisputeNotificationRequest.attributeTypeMap = [
    {
        "name": "data",
        "baseName": "data",
        "type": "DisputeEventNotification"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "DisputeNotificationRequest.TypeEnum"
    }
];
(function (DisputeNotificationRequest) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["Created"] = "balancePlatform.dispute.created";
        TypeEnum["Updated"] = "balancePlatform.dispute.updated";
    })(TypeEnum = DisputeNotificationRequest.TypeEnum || (DisputeNotificationRequest.TypeEnum = {}));
})(DisputeNotificationRequest = exports.DisputeNotificationRequest || (exports.DisputeNotificationRequest = {}));
//# sourceMappingURL=disputeNotificationRequest.js.map