"use strict";
/*
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DisputeEventNotification = void 0;
class DisputeEventNotification {
    static getAttributeTypeMap() {
        return DisputeEventNotification.attributeTypeMap;
    }
}
exports.DisputeEventNotification = DisputeEventNotification;
DisputeEventNotification.discriminator = undefined;
DisputeEventNotification.attributeTypeMap = [
    {
        "name": "arn",
        "baseName": "arn",
        "type": "string"
    },
    {
        "name": "balancePlatform",
        "baseName": "balancePlatform",
        "type": "string"
    },
    {
        "name": "creationDate",
        "baseName": "creationDate",
        "type": "Date"
    },
    {
        "name": "description",
        "baseName": "description",
        "type": "string"
    },
    {
        "name": "disputedAmount",
        "baseName": "disputedAmount",
        "type": "Amount | null"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "status",
        "baseName": "status",
        "type": "string"
    },
    {
        "name": "statusDetail",
        "baseName": "statusDetail",
        "type": "string"
    },
    {
        "name": "transactionId",
        "baseName": "transactionId",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "DisputeEventNotification.TypeEnum"
    }
];
(function (DisputeEventNotification) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["Fraud"] = "fraud";
        TypeEnum["NotDelivered"] = "notDelivered";
        TypeEnum["Duplicate"] = "duplicate";
    })(TypeEnum = DisputeEventNotification.TypeEnum || (DisputeEventNotification.TypeEnum = {}));
})(DisputeEventNotification = exports.DisputeEventNotification || (exports.DisputeEventNotification = {}));
//# sourceMappingURL=disputeEventNotification.js.map