"use strict";
/*
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BankAccountDetails = void 0;
class BankAccountDetails {
    static getAttributeTypeMap() {
        return BankAccountDetails.attributeTypeMap;
    }
}
exports.BankAccountDetails = BankAccountDetails;
BankAccountDetails.discriminator = undefined;
BankAccountDetails.attributeTypeMap = [
    {
        "name": "accountNumber",
        "baseName": "accountNumber",
        "type": "string"
    },
    {
        "name": "accountType",
        "baseName": "accountType",
        "type": "string"
    },
    {
        "name": "branchNumber",
        "baseName": "branchNumber",
        "type": "string"
    },
    {
        "name": "formFactor",
        "baseName": "formFactor",
        "type": "string"
    },
    {
        "name": "iban",
        "baseName": "iban",
        "type": "string"
    },
    {
        "name": "routingNumber",
        "baseName": "routingNumber",
        "type": "string"
    },
    {
        "name": "sortCode",
        "baseName": "sortCode",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    }
];
//# sourceMappingURL=bankAccountDetails.js.map