"use strict";
/*
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BoardingTokenResponse = void 0;
class BoardingTokenResponse {
    static getAttributeTypeMap() {
        return BoardingTokenResponse.attributeTypeMap;
    }
}
exports.BoardingTokenResponse = BoardingTokenResponse;
BoardingTokenResponse.discriminator = undefined;
BoardingTokenResponse.attributeTypeMap = [
    {
        "name": "boardingToken",
        "baseName": "boardingToken",
        "type": "string"
    },
    {
        "name": "installationId",
        "baseName": "installationId",
        "type": "string"
    }
];
//# sourceMappingURL=boardingTokenResponse.js.map