"use strict";
/*
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PaymentsAppResponse = void 0;
class PaymentsAppResponse {
    static getAttributeTypeMap() {
        return PaymentsAppResponse.attributeTypeMap;
    }
}
exports.PaymentsAppResponse = PaymentsAppResponse;
PaymentsAppResponse.discriminator = undefined;
PaymentsAppResponse.attributeTypeMap = [
    {
        "name": "paymentsApps",
        "baseName": "paymentsApps",
        "type": "Array<PaymentsAppDto>"
    }
];
//# sourceMappingURL=paymentsAppResponse.js.map