"use strict";
/*
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NegativeBalanceCompensationWarningNotificationData = void 0;
class NegativeBalanceCompensationWarningNotificationData {
    static getAttributeTypeMap() {
        return NegativeBalanceCompensationWarningNotificationData.attributeTypeMap;
    }
}
exports.NegativeBalanceCompensationWarningNotificationData = NegativeBalanceCompensationWarningNotificationData;
NegativeBalanceCompensationWarningNotificationData.discriminator = undefined;
NegativeBalanceCompensationWarningNotificationData.attributeTypeMap = [
    {
        "name": "accountHolder",
        "baseName": "accountHolder",
        "type": "ResourceReference | null"
    },
    {
        "name": "amount",
        "baseName": "amount",
        "type": "Amount | null"
    },
    {
        "name": "balancePlatform",
        "baseName": "balancePlatform",
        "type": "string"
    },
    {
        "name": "creationDate",
        "baseName": "creationDate",
        "type": "Date"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "liableBalanceAccountId",
        "baseName": "liableBalanceAccountId",
        "type": "string"
    },
    {
        "name": "negativeBalanceSince",
        "baseName": "negativeBalanceSince",
        "type": "Date"
    },
    {
        "name": "scheduledCompensationAt",
        "baseName": "scheduledCompensationAt",
        "type": "Date"
    }
];
//# sourceMappingURL=negativeBalanceCompensationWarningNotificationData.js.map