"use strict";
/*
 * The version of the OpenAPI document: v68
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApplicationInfo = void 0;
class ApplicationInfo {
    static getAttributeTypeMap() {
        return ApplicationInfo.attributeTypeMap;
    }
}
exports.ApplicationInfo = ApplicationInfo;
ApplicationInfo.discriminator = undefined;
ApplicationInfo.attributeTypeMap = [
    {
        "name": "adyenLibrary",
        "baseName": "adyenLibrary",
        "type": "CommonField | null"
    },
    {
        "name": "adyenPaymentSource",
        "baseName": "adyenPaymentSource",
        "type": "CommonField | null"
    },
    {
        "name": "externalPlatform",
        "baseName": "externalPlatform",
        "type": "ExternalPlatform | null"
    },
    {
        "name": "merchantApplication",
        "baseName": "merchantApplication",
        "type": "CommonField | null"
    },
    {
        "name": "merchantDevice",
        "baseName": "merchantDevice",
        "type": "MerchantDevice | null"
    },
    {
        "name": "shopperInteractionDevice",
        "baseName": "shopperInteractionDevice",
        "type": "ShopperInteractionDevice | null"
    }
];
//# sourceMappingURL=applicationInfo.js.map