"use strict";
/*
 * The version of the OpenAPI document: v68
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FundDestination = void 0;
class FundDestination {
    static getAttributeTypeMap() {
        return FundDestination.attributeTypeMap;
    }
}
exports.FundDestination = FundDestination;
FundDestination.discriminator = undefined;
FundDestination.attributeTypeMap = [
    {
        "name": "IBAN",
        "baseName": "IBAN",
        "type": "string"
    },
    {
        "name": "additionalData",
        "baseName": "additionalData",
        "type": "{ [key: string]: string; }"
    },
    {
        "name": "billingAddress",
        "baseName": "billingAddress",
        "type": "Address | null"
    },
    {
        "name": "card",
        "baseName": "card",
        "type": "Card | null"
    },
    {
        "name": "selectedRecurringDetailReference",
        "baseName": "selectedRecurringDetailReference",
        "type": "string"
    },
    {
        "name": "shopperEmail",
        "baseName": "shopperEmail",
        "type": "string"
    },
    {
        "name": "shopperName",
        "baseName": "shopperName",
        "type": "Name | null"
    },
    {
        "name": "shopperReference",
        "baseName": "shopperReference",
        "type": "string"
    },
    {
        "name": "subMerchant",
        "baseName": "subMerchant",
        "type": "SubMerchant | null"
    },
    {
        "name": "telephoneNumber",
        "baseName": "telephoneNumber",
        "type": "string"
    },
    {
        "name": "walletPurpose",
        "baseName": "walletPurpose",
        "type": "string"
    }
];
//# sourceMappingURL=fundDestination.js.map