export * from './accountCapabilityData';
export * from './accountCreateNotificationData';
export * from './accountNotificationResponse';
export * from './accountUpdateNotificationData';
export * from './capabilityProblem';
export * from './capabilityProblemEntity';
export * from './capabilityProblemEntityRecursive';
export * from './merchantCreatedNotificationRequest';
export * from './merchantUpdatedNotificationRequest';
export * from './midServiceNotificationData';
export * from './paymentMethodCreatedNotificationRequest';
export * from './paymentMethodNotificationResponse';
export * from './paymentMethodRequestRemovedNotificationRequest';
export * from './paymentMethodScheduledForRemovalNotificationRequest';
export * from './remediatingAction';
export * from './terminalAssignmentNotificationRequest';
export * from './terminalAssignmentNotificationResponse';
export * from './terminalBoardingData';
export * from './terminalBoardingNotificationRequest';
export * from './terminalBoardingNotificationResponse';
export * from './terminalSettingsData';
export * from './terminalSettingsNotificationRequest';
export * from './terminalSettingsNotificationResponse';
export * from './verificationError';
export * from './verificationErrorRecursive';
export declare class ObjectSerializer {
    static findCorrectType(data: any, expectedType: string): any;
    static serialize(data: any, type: string): any;
    static deserialize(data: any, type: string): any;
}
