"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TerminalAssignmentNotificationRequest = void 0;
class TerminalAssignmentNotificationRequest {
    static getAttributeTypeMap() {
        return TerminalAssignmentNotificationRequest.attributeTypeMap;
    }
}
exports.TerminalAssignmentNotificationRequest = TerminalAssignmentNotificationRequest;
TerminalAssignmentNotificationRequest.discriminator = undefined;
TerminalAssignmentNotificationRequest.attributeTypeMap = [
    {
        "name": "assignedToAccount",
        "baseName": "assignedToAccount",
        "type": "string"
    },
    {
        "name": "assignedToStore",
        "baseName": "assignedToStore",
        "type": "string"
    },
    {
        "name": "eventDate",
        "baseName": "eventDate",
        "type": "string"
    },
    {
        "name": "pspReference",
        "baseName": "pspReference",
        "type": "string"
    },
    {
        "name": "uniqueTerminalId",
        "baseName": "uniqueTerminalId",
        "type": "string"
    }
];
//# sourceMappingURL=terminalAssignmentNotificationRequest.js.map