"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TerminalAssignmentNotificationResponse = void 0;
class TerminalAssignmentNotificationResponse {
    static getAttributeTypeMap() {
        return TerminalAssignmentNotificationResponse.attributeTypeMap;
    }
}
exports.TerminalAssignmentNotificationResponse = TerminalAssignmentNotificationResponse;
TerminalAssignmentNotificationResponse.discriminator = undefined;
TerminalAssignmentNotificationResponse.attributeTypeMap = [
    {
        "name": "notificationResponse",
        "baseName": "notificationResponse",
        "type": "string"
    }
];
//# sourceMappingURL=terminalAssignmentNotificationResponse.js.map