"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TerminalSettingsNotificationRequest = void 0;
class TerminalSettingsNotificationRequest {
    static getAttributeTypeMap() {
        return TerminalSettingsNotificationRequest.attributeTypeMap;
    }
}
exports.TerminalSettingsNotificationRequest = TerminalSettingsNotificationRequest;
TerminalSettingsNotificationRequest.discriminator = undefined;
TerminalSettingsNotificationRequest.attributeTypeMap = [
    {
        "name": "createdAt",
        "baseName": "createdAt",
        "type": "Date"
    },
    {
        "name": "data",
        "baseName": "data",
        "type": "TerminalSettingsData"
    },
    {
        "name": "environment",
        "baseName": "environment",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "TerminalSettingsNotificationRequest.TypeEnum"
    }
];
(function (TerminalSettingsNotificationRequest) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["TerminalSettingsModified"] = "terminalSettings.modified";
    })(TypeEnum = TerminalSettingsNotificationRequest.TypeEnum || (TerminalSettingsNotificationRequest.TypeEnum = {}));
})(TerminalSettingsNotificationRequest = exports.TerminalSettingsNotificationRequest || (exports.TerminalSettingsNotificationRequest = {}));
//# sourceMappingURL=terminalSettingsNotificationRequest.js.map