"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TerminalBoardingNotificationRequest = void 0;
class TerminalBoardingNotificationRequest {
    static getAttributeTypeMap() {
        return TerminalBoardingNotificationRequest.attributeTypeMap;
    }
}
exports.TerminalBoardingNotificationRequest = TerminalBoardingNotificationRequest;
TerminalBoardingNotificationRequest.discriminator = undefined;
TerminalBoardingNotificationRequest.attributeTypeMap = [
    {
        "name": "createdAt",
        "baseName": "createdAt",
        "type": "Date"
    },
    {
        "name": "data",
        "baseName": "data",
        "type": "TerminalBoardingData"
    },
    {
        "name": "environment",
        "baseName": "environment",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "TerminalBoardingNotificationRequest.TypeEnum"
    }
];
(function (TerminalBoardingNotificationRequest) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum["TerminalBoardingTriggered"] = "terminalBoarding.triggered";
    })(TypeEnum = TerminalBoardingNotificationRequest.TypeEnum || (TerminalBoardingNotificationRequest.TypeEnum = {}));
})(TerminalBoardingNotificationRequest = exports.TerminalBoardingNotificationRequest || (exports.TerminalBoardingNotificationRequest = {}));
//# sourceMappingURL=terminalBoardingNotificationRequest.js.map