"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TerminalSettingsNotificationResponse = void 0;
class TerminalSettingsNotificationResponse {
    static getAttributeTypeMap() {
        return TerminalSettingsNotificationResponse.attributeTypeMap;
    }
}
exports.TerminalSettingsNotificationResponse = TerminalSettingsNotificationResponse;
TerminalSettingsNotificationResponse.discriminator = undefined;
TerminalSettingsNotificationResponse.attributeTypeMap = [
    {
        "name": "notificationResponse",
        "baseName": "notificationResponse",
        "type": "string"
    }
];
//# sourceMappingURL=terminalSettingsNotificationResponse.js.map