"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TerminalBoardingData = void 0;
class TerminalBoardingData {
    static getAttributeTypeMap() {
        return TerminalBoardingData.attributeTypeMap;
    }
}
exports.TerminalBoardingData = TerminalBoardingData;
TerminalBoardingData.discriminator = undefined;
TerminalBoardingData.attributeTypeMap = [
    {
        "name": "companyId",
        "baseName": "companyId",
        "type": "string"
    },
    {
        "name": "merchantId",
        "baseName": "merchantId",
        "type": "string"
    },
    {
        "name": "storeId",
        "baseName": "storeId",
        "type": "string"
    },
    {
        "name": "uniqueTerminalId",
        "baseName": "uniqueTerminalId",
        "type": "string"
    }
];
//# sourceMappingURL=terminalBoardingData.js.map