"use strict";
/*
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TerminalSettingsData = void 0;
class TerminalSettingsData {
    static getAttributeTypeMap() {
        return TerminalSettingsData.attributeTypeMap;
    }
}
exports.TerminalSettingsData = TerminalSettingsData;
TerminalSettingsData.discriminator = undefined;
TerminalSettingsData.attributeTypeMap = [
    {
        "name": "companyId",
        "baseName": "companyId",
        "type": "string"
    },
    {
        "name": "merchantId",
        "baseName": "merchantId",
        "type": "string"
    },
    {
        "name": "storeId",
        "baseName": "storeId",
        "type": "string"
    },
    {
        "name": "terminalId",
        "baseName": "terminalId",
        "type": "string"
    },
    {
        "name": "updateSource",
        "baseName": "updateSource",
        "type": "TerminalSettingsData.UpdateSourceEnum"
    },
    {
        "name": "user",
        "baseName": "user",
        "type": "string"
    }
];
(function (TerminalSettingsData) {
    let UpdateSourceEnum;
    (function (UpdateSourceEnum) {
        UpdateSourceEnum["CustomerArea"] = "Customer Area";
        UpdateSourceEnum["ManagementApi"] = "Management Api";
    })(UpdateSourceEnum = TerminalSettingsData.UpdateSourceEnum || (TerminalSettingsData.UpdateSourceEnum = {}));
})(TerminalSettingsData = exports.TerminalSettingsData || (exports.TerminalSettingsData = {}));
//# sourceMappingURL=terminalSettingsData.js.map